/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_expl_ode_fun:(i0[11],i1[4],i2[15])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+11, *w1=w+22, *w2=w+43, *w3=w+52, *w4=w+61, w5, w6, w7, w8, *w9=w+74, w10, *w11=w+79, *w12=w+88, *w13=w+91, *w14=w+124, *w15=w+157, w16, w17, w18, w19, w20, *w21=w+174, *w22=w+178, *w23=w+182, *w24=w+186, *w25=w+202, *w26=w+218, *w27=w+262, *w28=w+306, *w29=w+334, *w30=w+350, *w31=w+366, *w32=w+410, *w33=w+531, w34, *w35=w+653;
  /* #0: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #1: @1 = zeros(3x7) */
  casadi_clear(w1, 21);
  /* #2: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w2);
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #5: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = vertcat(@5, @6, @7, @8) */
  rr=w9;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #10: @10 = ||@9||_F */
  w10 = sqrt(casadi_dot(4, w9, w9));
  /* #11: @9 = (@9/@10) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w10;
  /* #12: @10 = @9[3] */
  for (rr=(&w10), ss=w9+3; ss!=w9+4; ss+=1) *rr++ = *ss;
  /* #13: @10 = (-@10) */
  w10 = (- w10 );
  /* #14: (@4[3] = @10) */
  for (rr=w4+3, ss=(&w10); rr!=w4+4; rr+=1) *rr = *ss++;
  /* #15: @10 = @9[2] */
  for (rr=(&w10), ss=w9+2; ss!=w9+3; ss+=1) *rr++ = *ss;
  /* #16: (@4[6] = @10) */
  for (rr=w4+6, ss=(&w10); rr!=w4+7; rr+=1) *rr = *ss++;
  /* #17: @10 = @9[1] */
  for (rr=(&w10), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #18: @10 = (-@10) */
  w10 = (- w10 );
  /* #19: (@4[7] = @10) */
  for (rr=w4+7, ss=(&w10); rr!=w4+8; rr+=1) *rr = *ss++;
  /* #20: @10 = @9[3] */
  for (rr=(&w10), ss=w9+3; ss!=w9+4; ss+=1) *rr++ = *ss;
  /* #21: (@4[1] = @10) */
  for (rr=w4+1, ss=(&w10); rr!=w4+2; rr+=1) *rr = *ss++;
  /* #22: @10 = @9[2] */
  for (rr=(&w10), ss=w9+2; ss!=w9+3; ss+=1) *rr++ = *ss;
  /* #23: @10 = (-@10) */
  w10 = (- w10 );
  /* #24: (@4[2] = @10) */
  for (rr=w4+2, ss=(&w10); rr!=w4+3; rr+=1) *rr = *ss++;
  /* #25: @10 = @9[1] */
  for (rr=(&w10), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #26: (@4[5] = @10) */
  for (rr=w4+5, ss=(&w10); rr!=w4+6; rr+=1) *rr = *ss++;
  /* #27: @11 = (2.*@4) */
  for (i=0, rr=w11, cs=w4; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #28: @3 = mac(@11,@4,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w11+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #29: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #30: @10 = @9[0] */
  for (rr=(&w10), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #31: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #32: @4 = (@10*@4) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) (*rr++)  = (w10*(*cs++));
  /* #33: @2 = (@2+@4) */
  for (i=0, rr=w2, cs=w4; i<9; ++i) (*rr++) += (*cs++);
  /* #34: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #35: @13 = horzcat(@1, @2, @12) */
  rr=w13;
  for (i=0, cs=w1; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #36: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #37: @15 = zeros(4x3) */
  casadi_clear(w15, 12);
  /* #38: @10 = 0.5 */
  w10 = 5.0000000000000000e-01;
  /* #39: @16 = 0 */
  w16 = 0.;
  /* #40: @17 = 0 */
  w17 = 0.;
  /* #41: @18 = 0 */
  w18 = 0.;
  /* #42: @19 = input[0][10] */
  w19 = arg[0] ? arg[0][10] : 0;
  /* #43: @20 = (-@19) */
  w20 = (- w19 );
  /* #44: @9 = horzcat(@16, @17, @18, @20) */
  rr=w9;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w20;
  /* #45: @9 = @9' */
  /* #46: @16 = 0 */
  w16 = 0.;
  /* #47: @17 = 0 */
  w17 = 0.;
  /* #48: @18 = 0 */
  w18 = 0.;
  /* #49: @21 = horzcat(@16, @17, @19, @18) */
  rr=w21;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w18;
  /* #50: @21 = @21' */
  /* #51: @16 = 0 */
  w16 = 0.;
  /* #52: @17 = (-@19) */
  w17 = (- w19 );
  /* #53: @18 = 0 */
  w18 = 0.;
  /* #54: @20 = 0 */
  w20 = 0.;
  /* #55: @22 = horzcat(@16, @17, @18, @20) */
  rr=w22;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w20;
  /* #56: @22 = @22' */
  /* #57: @16 = 0 */
  w16 = 0.;
  /* #58: @17 = 0 */
  w17 = 0.;
  /* #59: @18 = 0 */
  w18 = 0.;
  /* #60: @23 = horzcat(@19, @16, @17, @18) */
  rr=w23;
  *rr++ = w19;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #61: @23 = @23' */
  /* #62: @24 = horzcat(@9, @21, @22, @23) */
  rr=w24;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<4; ++i) *rr++ = *cs++;
  /* #63: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #64: @25 = (@10*@25) */
  for (i=0, rr=w25, cs=w25; i<16; ++i) (*rr++)  = (w10*(*cs++));
  /* #65: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #66: @26 = horzcat(@15, @25, @24) */
  rr=w26;
  for (i=0, cs=w15; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  /* #67: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #68: @28 = zeros(4x7) */
  casadi_clear(w28, 28);
  /* #69: @25 = zeros(4x4) */
  casadi_clear(w25, 16);
  /* #70: @24 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w24);
  /* #71: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #72: @10 = 0.6756 */
  w10 = 6.7559999999999998e-01;
  /* #73: (@29[0] = @10) */
  for (rr=w29+0, ss=(&w10); rr!=w29+1; rr+=1) *rr = *ss++;
  /* #74: @10 = 0 */
  w10 = 0.;
  /* #75: (@29[4] = @10) */
  for (rr=w29+4, ss=(&w10); rr!=w29+5; rr+=1) *rr = *ss++;
  /* #76: @10 = 0 */
  w10 = 0.;
  /* #77: (@29[8] = @10) */
  for (rr=w29+8, ss=(&w10); rr!=w29+9; rr+=1) *rr = *ss++;
  /* #78: @10 = 0 */
  w10 = 0.;
  /* #79: (@29[12] = @10) */
  for (rr=w29+12, ss=(&w10); rr!=w29+13; rr+=1) *rr = *ss++;
  /* #80: @10 = 0 */
  w10 = 0.;
  /* #81: (@29[1] = @10) */
  for (rr=w29+1, ss=(&w10); rr!=w29+2; rr+=1) *rr = *ss++;
  /* #82: @10 = 0.6344 */
  w10 = 6.3439999999999996e-01;
  /* #83: (@29[5] = @10) */
  for (rr=w29+5, ss=(&w10); rr!=w29+6; rr+=1) *rr = *ss++;
  /* #84: @10 = 0 */
  w10 = 0.;
  /* #85: (@29[9] = @10) */
  for (rr=w29+9, ss=(&w10); rr!=w29+10; rr+=1) *rr = *ss++;
  /* #86: @10 = 0 */
  w10 = 0.;
  /* #87: (@29[13] = @10) */
  for (rr=w29+13, ss=(&w10); rr!=w29+14; rr+=1) *rr = *ss++;
  /* #88: @10 = 0 */
  w10 = 0.;
  /* #89: (@29[2] = @10) */
  for (rr=w29+2, ss=(&w10); rr!=w29+3; rr+=1) *rr = *ss++;
  /* #90: @10 = 0 */
  w10 = 0.;
  /* #91: (@29[6] = @10) */
  for (rr=w29+6, ss=(&w10); rr!=w29+7; rr+=1) *rr = *ss++;
  /* #92: @10 = 0.408 */
  w10 = 4.0799999999999997e-01;
  /* #93: (@29[10] = @10) */
  for (rr=w29+10, ss=(&w10); rr!=w29+11; rr+=1) *rr = *ss++;
  /* #94: @10 = 0 */
  w10 = 0.;
  /* #95: (@29[14] = @10) */
  for (rr=w29+14, ss=(&w10); rr!=w29+15; rr+=1) *rr = *ss++;
  /* #96: @10 = 0 */
  w10 = 0.;
  /* #97: (@29[3] = @10) */
  for (rr=w29+3, ss=(&w10); rr!=w29+4; rr+=1) *rr = *ss++;
  /* #98: @10 = 0 */
  w10 = 0.;
  /* #99: (@29[7] = @10) */
  for (rr=w29+7, ss=(&w10); rr!=w29+8; rr+=1) *rr = *ss++;
  /* #100: @10 = 0 */
  w10 = 0.;
  /* #101: (@29[11] = @10) */
  for (rr=w29+11, ss=(&w10); rr!=w29+12; rr+=1) *rr = *ss++;
  /* #102: @10 = 0.2953 */
  w10 = 2.9530000000000001e-01;
  /* #103: (@29[15] = @10) */
  for (rr=w29+15, ss=(&w10); rr!=w29+16; rr+=1) *rr = *ss++;
  /* #104: @24 = (@29\@24) */
  rr = w24;
  ss = w29;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #105: @30 = zeros(4x4) */
  casadi_clear(w30, 16);
  /* #106: @10 = 0.5941 */
  w10 = 5.9409999999999996e-01;
  /* #107: (@30[0] = @10) */
  for (rr=w30+0, ss=(&w10); rr!=w30+1; rr+=1) *rr = *ss++;
  /* #108: @10 = -0.8109 */
  w10 = -8.1089999999999995e-01;
  /* #109: @10 = (@10*@19) */
  w10 *= w19;
  /* #110: (@30[4] = @10) */
  for (rr=w30+4, ss=(&w10); rr!=w30+5; rr+=1) *rr = *ss++;
  /* #111: @10 = 0 */
  w10 = 0.;
  /* #112: (@30[8] = @10) */
  for (rr=w30+8, ss=(&w10); rr!=w30+9; rr+=1) *rr = *ss++;
  /* #113: @10 = 0 */
  w10 = 0.;
  /* #114: (@30[12] = @10) */
  for (rr=w30+12, ss=(&w10); rr!=w30+13; rr+=1) *rr = *ss++;
  /* #115: @10 = 0.3984 */
  w10 = 3.9839999999999998e-01;
  /* #116: @10 = (@10*@19) */
  w10 *= w19;
  /* #117: (@30[1] = @10) */
  for (rr=w30+1, ss=(&w10); rr!=w30+2; rr+=1) *rr = *ss++;
  /* #118: @10 = 0.704 */
  w10 = 7.0399999999999996e-01;
  /* #119: (@30[5] = @10) */
  for (rr=w30+5, ss=(&w10); rr!=w30+6; rr+=1) *rr = *ss++;
  /* #120: @10 = 0 */
  w10 = 0.;
  /* #121: (@30[9] = @10) */
  for (rr=w30+9, ss=(&w10); rr!=w30+10; rr+=1) *rr = *ss++;
  /* #122: @10 = 0 */
  w10 = 0.;
  /* #123: (@30[13] = @10) */
  for (rr=w30+13, ss=(&w10); rr!=w30+14; rr+=1) *rr = *ss++;
  /* #124: @10 = 0 */
  w10 = 0.;
  /* #125: (@30[2] = @10) */
  for (rr=w30+2, ss=(&w10); rr!=w30+3; rr+=1) *rr = *ss++;
  /* #126: @10 = 0 */
  w10 = 0.;
  /* #127: (@30[6] = @10) */
  for (rr=w30+6, ss=(&w10); rr!=w30+7; rr+=1) *rr = *ss++;
  /* #128: @10 = 0.9365 */
  w10 = 9.3650000000000000e-01;
  /* #129: (@30[10] = @10) */
  for (rr=w30+10, ss=(&w10); rr!=w30+11; rr+=1) *rr = *ss++;
  /* #130: @10 = 0 */
  w10 = 0.;
  /* #131: (@30[14] = @10) */
  for (rr=w30+14, ss=(&w10); rr!=w30+15; rr+=1) *rr = *ss++;
  /* #132: @10 = 0 */
  w10 = 0.;
  /* #133: (@30[3] = @10) */
  for (rr=w30+3, ss=(&w10); rr!=w30+4; rr+=1) *rr = *ss++;
  /* #134: @10 = 0 */
  w10 = 0.;
  /* #135: (@30[7] = @10) */
  for (rr=w30+7, ss=(&w10); rr!=w30+8; rr+=1) *rr = *ss++;
  /* #136: @10 = 0 */
  w10 = 0.;
  /* #137: (@30[11] = @10) */
  for (rr=w30+11, ss=(&w10); rr!=w30+12; rr+=1) *rr = *ss++;
  /* #138: @10 = 0.9752 */
  w10 = 9.7519999999999996e-01;
  /* #139: (@30[15] = @10) */
  for (rr=w30+15, ss=(&w10); rr!=w30+16; rr+=1) *rr = *ss++;
  /* #140: @25 = mac(@24,@30,@25) */
  for (i=0, rr=w25; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w24+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #141: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<16; ++i) *rr++ = (- *cs++ );
  /* #142: @26 = horzcat(@28, @25) */
  rr=w26;
  for (i=0, cs=w28; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<16; ++i) *rr++ = *cs++;
  /* #143: @31 = @26' */
  for (i=0, rr=w31, cs=w26; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #144: @32 = horzcat(@14, @27, @31) */
  rr=w32;
  for (i=0, cs=w14; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<44; ++i) *rr++ = *cs++;
  /* #145: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #146: @10 = input[0][0] */
  w10 = arg[0] ? arg[0][0] : 0;
  /* #147: @16 = input[0][1] */
  w16 = arg[0] ? arg[0][1] : 0;
  /* #148: @17 = input[0][2] */
  w17 = arg[0] ? arg[0][2] : 0;
  /* #149: @18 = input[0][7] */
  w18 = arg[0] ? arg[0][7] : 0;
  /* #150: @20 = input[0][8] */
  w20 = arg[0] ? arg[0][8] : 0;
  /* #151: @34 = input[0][9] */
  w34 = arg[0] ? arg[0][9] : 0;
  /* #152: @35 = vertcat(@10, @16, @17, @5, @6, @7, @8, @18, @20, @34, @19) */
  rr=w35;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w18;
  *rr++ = w20;
  *rr++ = w34;
  *rr++ = w19;
  /* #153: @0 = mac(@33,@35,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w33+j, tt=w35+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #154: @35 = zeros(11x1) */
  casadi_clear(w35, 11);
  /* #155: @28 = zeros(4x7) */
  casadi_clear(w28, 28);
  /* #156: @25 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w25);
  /* #157: @25 = (@29\@25) */
  rr = w25;
  ss = w29;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #158: @29 = @25' */
  for (i=0, rr=w29, cs=w25; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #159: @27 = horzcat(@28, @29) */
  rr=w27;
  for (i=0, cs=w28; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<16; ++i) *rr++ = *cs++;
  /* #160: @31 = @27' */
  for (i=0, rr=w31, cs=w27; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #161: @10 = input[1][0] */
  w10 = arg[1] ? arg[1][0] : 0;
  /* #162: @16 = input[1][1] */
  w16 = arg[1] ? arg[1][1] : 0;
  /* #163: @17 = input[1][2] */
  w17 = arg[1] ? arg[1][2] : 0;
  /* #164: @5 = input[1][3] */
  w5 = arg[1] ? arg[1][3] : 0;
  /* #165: @9 = vertcat(@10, @16, @17, @5) */
  rr=w9;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w5;
  /* #166: @35 = mac(@31,@9,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w31+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*11]**tt++;
  /* #167: @0 = (@0+@35) */
  for (i=0, rr=w0, cs=w35; i<11; ++i) (*rr++) += (*cs++);
  /* #168: output[0][0] = @0 */
  casadi_copy(w0, 11, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 664;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
