/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_expl_vde_adj:(i0[11],i1[11],i2[4],i3[15])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+11, *w1=w+22, *w2=w+43, *w3=w+52, *w4=w+61, w5, w6, w7, w8, *w9=w+74, w10, *w11=w+79, w12, *w13=w+84, *w14=w+93, *w15=w+96, *w16=w+129, *w17=w+162, w18, w19, w20, w21, w22, w23, *w24=w+180, *w25=w+184, *w26=w+188, *w27=w+192, *w28=w+196, *w29=w+212, *w30=w+228, *w31=w+272, *w32=w+316, *w33=w+344, *w34=w+360, *w35=w+376, *w36=w+420, *w37=w+541, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, *w50=w+564, *w51=w+685, *w52=w+694;
  /* #0: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #1: @1 = zeros(3x7) */
  casadi_clear(w1, 21);
  /* #2: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w2);
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #5: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = vertcat(@5, @6, @7, @8) */
  rr=w9;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #10: @10 = ||@9||_F */
  w10 = sqrt(casadi_dot(4, w9, w9));
  /* #11: @11 = (@9/@10) */
  for (i=0, rr=w11, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #12: @12 = @11[3] */
  for (rr=(&w12), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #13: @12 = (-@12) */
  w12 = (- w12 );
  /* #14: (@4[3] = @12) */
  for (rr=w4+3, ss=(&w12); rr!=w4+4; rr+=1) *rr = *ss++;
  /* #15: @12 = @11[2] */
  for (rr=(&w12), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #16: (@4[6] = @12) */
  for (rr=w4+6, ss=(&w12); rr!=w4+7; rr+=1) *rr = *ss++;
  /* #17: @12 = @11[1] */
  for (rr=(&w12), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #18: @12 = (-@12) */
  w12 = (- w12 );
  /* #19: (@4[7] = @12) */
  for (rr=w4+7, ss=(&w12); rr!=w4+8; rr+=1) *rr = *ss++;
  /* #20: @12 = @11[3] */
  for (rr=(&w12), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #21: (@4[1] = @12) */
  for (rr=w4+1, ss=(&w12); rr!=w4+2; rr+=1) *rr = *ss++;
  /* #22: @12 = @11[2] */
  for (rr=(&w12), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #23: @12 = (-@12) */
  w12 = (- w12 );
  /* #24: (@4[2] = @12) */
  for (rr=w4+2, ss=(&w12); rr!=w4+3; rr+=1) *rr = *ss++;
  /* #25: @12 = @11[1] */
  for (rr=(&w12), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #26: (@4[5] = @12) */
  for (rr=w4+5, ss=(&w12); rr!=w4+6; rr+=1) *rr = *ss++;
  /* #27: @13 = (2.*@4) */
  for (i=0, rr=w13, cs=w4; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #28: @3 = mac(@13,@4,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #29: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #30: @12 = @11[0] */
  for (rr=(&w12), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #31: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #32: @3 = (@12*@4) */
  for (i=0, rr=w3, cs=w4; i<9; ++i) (*rr++)  = (w12*(*cs++));
  /* #33: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #34: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #35: @15 = horzcat(@1, @2, @14) */
  rr=w15;
  for (i=0, cs=w1; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #36: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #37: @17 = zeros(4x3) */
  casadi_clear(w17, 12);
  /* #38: @18 = 0.5 */
  w18 = 5.0000000000000000e-01;
  /* #39: @19 = 0 */
  w19 = 0.;
  /* #40: @20 = 0 */
  w20 = 0.;
  /* #41: @21 = 0 */
  w21 = 0.;
  /* #42: @22 = input[0][10] */
  w22 = arg[0] ? arg[0][10] : 0;
  /* #43: @23 = (-@22) */
  w23 = (- w22 );
  /* #44: @24 = horzcat(@19, @20, @21, @23) */
  rr=w24;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w23;
  /* #45: @24 = @24' */
  /* #46: @19 = 0 */
  w19 = 0.;
  /* #47: @20 = 0 */
  w20 = 0.;
  /* #48: @21 = 0 */
  w21 = 0.;
  /* #49: @25 = horzcat(@19, @20, @22, @21) */
  rr=w25;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w21;
  /* #50: @25 = @25' */
  /* #51: @19 = 0 */
  w19 = 0.;
  /* #52: @20 = (-@22) */
  w20 = (- w22 );
  /* #53: @21 = 0 */
  w21 = 0.;
  /* #54: @23 = 0 */
  w23 = 0.;
  /* #55: @26 = horzcat(@19, @20, @21, @23) */
  rr=w26;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w23;
  /* #56: @26 = @26' */
  /* #57: @19 = 0 */
  w19 = 0.;
  /* #58: @20 = 0 */
  w20 = 0.;
  /* #59: @21 = 0 */
  w21 = 0.;
  /* #60: @27 = horzcat(@22, @19, @20, @21) */
  rr=w27;
  *rr++ = w22;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #61: @27 = @27' */
  /* #62: @28 = horzcat(@24, @25, @26, @27) */
  rr=w28;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  /* #63: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #64: @29 = (@18*@29) */
  for (i=0, rr=w29, cs=w29; i<16; ++i) (*rr++)  = (w18*(*cs++));
  /* #65: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #66: @30 = horzcat(@17, @29, @28) */
  rr=w30;
  for (i=0, cs=w17; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<16; ++i) *rr++ = *cs++;
  /* #67: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #68: @32 = zeros(4x7) */
  casadi_clear(w32, 28);
  /* #69: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #70: @28 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w28);
  /* #71: @33 = zeros(4x4) */
  casadi_clear(w33, 16);
  /* #72: @19 = 0.6756 */
  w19 = 6.7559999999999998e-01;
  /* #73: (@33[0] = @19) */
  for (rr=w33+0, ss=(&w19); rr!=w33+1; rr+=1) *rr = *ss++;
  /* #74: @19 = 0 */
  w19 = 0.;
  /* #75: (@33[4] = @19) */
  for (rr=w33+4, ss=(&w19); rr!=w33+5; rr+=1) *rr = *ss++;
  /* #76: @19 = 0 */
  w19 = 0.;
  /* #77: (@33[8] = @19) */
  for (rr=w33+8, ss=(&w19); rr!=w33+9; rr+=1) *rr = *ss++;
  /* #78: @19 = 0 */
  w19 = 0.;
  /* #79: (@33[12] = @19) */
  for (rr=w33+12, ss=(&w19); rr!=w33+13; rr+=1) *rr = *ss++;
  /* #80: @19 = 0 */
  w19 = 0.;
  /* #81: (@33[1] = @19) */
  for (rr=w33+1, ss=(&w19); rr!=w33+2; rr+=1) *rr = *ss++;
  /* #82: @19 = 0.6344 */
  w19 = 6.3439999999999996e-01;
  /* #83: (@33[5] = @19) */
  for (rr=w33+5, ss=(&w19); rr!=w33+6; rr+=1) *rr = *ss++;
  /* #84: @19 = 0 */
  w19 = 0.;
  /* #85: (@33[9] = @19) */
  for (rr=w33+9, ss=(&w19); rr!=w33+10; rr+=1) *rr = *ss++;
  /* #86: @19 = 0 */
  w19 = 0.;
  /* #87: (@33[13] = @19) */
  for (rr=w33+13, ss=(&w19); rr!=w33+14; rr+=1) *rr = *ss++;
  /* #88: @19 = 0 */
  w19 = 0.;
  /* #89: (@33[2] = @19) */
  for (rr=w33+2, ss=(&w19); rr!=w33+3; rr+=1) *rr = *ss++;
  /* #90: @19 = 0 */
  w19 = 0.;
  /* #91: (@33[6] = @19) */
  for (rr=w33+6, ss=(&w19); rr!=w33+7; rr+=1) *rr = *ss++;
  /* #92: @19 = 0.408 */
  w19 = 4.0799999999999997e-01;
  /* #93: (@33[10] = @19) */
  for (rr=w33+10, ss=(&w19); rr!=w33+11; rr+=1) *rr = *ss++;
  /* #94: @19 = 0 */
  w19 = 0.;
  /* #95: (@33[14] = @19) */
  for (rr=w33+14, ss=(&w19); rr!=w33+15; rr+=1) *rr = *ss++;
  /* #96: @19 = 0 */
  w19 = 0.;
  /* #97: (@33[3] = @19) */
  for (rr=w33+3, ss=(&w19); rr!=w33+4; rr+=1) *rr = *ss++;
  /* #98: @19 = 0 */
  w19 = 0.;
  /* #99: (@33[7] = @19) */
  for (rr=w33+7, ss=(&w19); rr!=w33+8; rr+=1) *rr = *ss++;
  /* #100: @19 = 0 */
  w19 = 0.;
  /* #101: (@33[11] = @19) */
  for (rr=w33+11, ss=(&w19); rr!=w33+12; rr+=1) *rr = *ss++;
  /* #102: @19 = 0.2953 */
  w19 = 2.9530000000000001e-01;
  /* #103: (@33[15] = @19) */
  for (rr=w33+15, ss=(&w19); rr!=w33+16; rr+=1) *rr = *ss++;
  /* #104: @28 = (@33\@28) */
  rr = w28;
  ss = w33;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #105: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #106: @19 = 0.5941 */
  w19 = 5.9409999999999996e-01;
  /* #107: (@34[0] = @19) */
  for (rr=w34+0, ss=(&w19); rr!=w34+1; rr+=1) *rr = *ss++;
  /* #108: @19 = -0.8109 */
  w19 = -8.1089999999999995e-01;
  /* #109: @20 = (@19*@22) */
  w20  = (w19*w22);
  /* #110: (@34[4] = @20) */
  for (rr=w34+4, ss=(&w20); rr!=w34+5; rr+=1) *rr = *ss++;
  /* #111: @20 = 0 */
  w20 = 0.;
  /* #112: (@34[8] = @20) */
  for (rr=w34+8, ss=(&w20); rr!=w34+9; rr+=1) *rr = *ss++;
  /* #113: @20 = 0 */
  w20 = 0.;
  /* #114: (@34[12] = @20) */
  for (rr=w34+12, ss=(&w20); rr!=w34+13; rr+=1) *rr = *ss++;
  /* #115: @20 = 0.3984 */
  w20 = 3.9839999999999998e-01;
  /* #116: @21 = (@20*@22) */
  w21  = (w20*w22);
  /* #117: (@34[1] = @21) */
  for (rr=w34+1, ss=(&w21); rr!=w34+2; rr+=1) *rr = *ss++;
  /* #118: @21 = 0.704 */
  w21 = 7.0399999999999996e-01;
  /* #119: (@34[5] = @21) */
  for (rr=w34+5, ss=(&w21); rr!=w34+6; rr+=1) *rr = *ss++;
  /* #120: @21 = 0 */
  w21 = 0.;
  /* #121: (@34[9] = @21) */
  for (rr=w34+9, ss=(&w21); rr!=w34+10; rr+=1) *rr = *ss++;
  /* #122: @21 = 0 */
  w21 = 0.;
  /* #123: (@34[13] = @21) */
  for (rr=w34+13, ss=(&w21); rr!=w34+14; rr+=1) *rr = *ss++;
  /* #124: @21 = 0 */
  w21 = 0.;
  /* #125: (@34[2] = @21) */
  for (rr=w34+2, ss=(&w21); rr!=w34+3; rr+=1) *rr = *ss++;
  /* #126: @21 = 0 */
  w21 = 0.;
  /* #127: (@34[6] = @21) */
  for (rr=w34+6, ss=(&w21); rr!=w34+7; rr+=1) *rr = *ss++;
  /* #128: @21 = 0.9365 */
  w21 = 9.3650000000000000e-01;
  /* #129: (@34[10] = @21) */
  for (rr=w34+10, ss=(&w21); rr!=w34+11; rr+=1) *rr = *ss++;
  /* #130: @21 = 0 */
  w21 = 0.;
  /* #131: (@34[14] = @21) */
  for (rr=w34+14, ss=(&w21); rr!=w34+15; rr+=1) *rr = *ss++;
  /* #132: @21 = 0 */
  w21 = 0.;
  /* #133: (@34[3] = @21) */
  for (rr=w34+3, ss=(&w21); rr!=w34+4; rr+=1) *rr = *ss++;
  /* #134: @21 = 0 */
  w21 = 0.;
  /* #135: (@34[7] = @21) */
  for (rr=w34+7, ss=(&w21); rr!=w34+8; rr+=1) *rr = *ss++;
  /* #136: @21 = 0 */
  w21 = 0.;
  /* #137: (@34[11] = @21) */
  for (rr=w34+11, ss=(&w21); rr!=w34+12; rr+=1) *rr = *ss++;
  /* #138: @21 = 0.9752 */
  w21 = 9.7519999999999996e-01;
  /* #139: (@34[15] = @21) */
  for (rr=w34+15, ss=(&w21); rr!=w34+16; rr+=1) *rr = *ss++;
  /* #140: @29 = mac(@28,@34,@29) */
  for (i=0, rr=w29; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w34+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #141: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<16; ++i) *rr++ = (- *cs++ );
  /* #142: @30 = horzcat(@32, @29) */
  rr=w30;
  for (i=0, cs=w32; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<16; ++i) *rr++ = *cs++;
  /* #143: @35 = @30' */
  for (i=0, rr=w35, cs=w30; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #144: @36 = horzcat(@16, @31, @35) */
  rr=w36;
  for (i=0, cs=w16; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<44; ++i) *rr++ = *cs++;
  /* #145: @37 = input[1][0] */
  casadi_copy(arg[1], 11, w37);
  /* #146: @0 = mac(@36,@37,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w36+j, tt=w37+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #147: {@21, @23, @38, @39, @40, @41, @42, @43, @44, @45, @46} = vertsplit(@0) */
  w21 = w0[0];
  w23 = w0[1];
  w38 = w0[2];
  w39 = w0[3];
  w40 = w0[4];
  w41 = w0[5];
  w42 = w0[6];
  w43 = w0[7];
  w44 = w0[8];
  w45 = w0[9];
  w46 = w0[10];
  /* #148: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  /* #149: output[0][1] = @23 */
  if (res[0]) res[0][1] = w23;
  /* #150: output[0][2] = @38 */
  if (res[0]) res[0][2] = w38;
  /* #151: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #152: @36 = zeros(11x11) */
  casadi_clear(w36, 121);
  /* #153: @38 = input[0][0] */
  w38 = arg[0] ? arg[0][0] : 0;
  /* #154: @23 = input[0][1] */
  w23 = arg[0] ? arg[0][1] : 0;
  /* #155: @21 = input[0][2] */
  w21 = arg[0] ? arg[0][2] : 0;
  /* #156: @47 = input[0][7] */
  w47 = arg[0] ? arg[0][7] : 0;
  /* #157: @48 = input[0][8] */
  w48 = arg[0] ? arg[0][8] : 0;
  /* #158: @49 = input[0][9] */
  w49 = arg[0] ? arg[0][9] : 0;
  /* #159: @0 = vertcat(@38, @23, @21, @5, @6, @7, @8, @47, @48, @49, @22) */
  rr=w0;
  *rr++ = w38;
  *rr++ = w23;
  *rr++ = w21;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w49;
  *rr++ = w22;
  /* #160: @0 = @0' */
  /* #161: @36 = mac(@37,@0,@36) */
  for (i=0, rr=w36; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w37+j, tt=w0+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #162: @50 = @36' */
  for (i=0, rr=w50, cs=w36; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #163: {@16, @31, @35} = horzsplit(@50) */
  casadi_copy(w50, 33, w16);
  casadi_copy(w50+33, 44, w31);
  casadi_copy(w50+77, 44, w35);
  /* #164: @15 = @16' */
  for (i=0, rr=w15, cs=w16; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #165: {NULL, @2, NULL} = horzsplit(@15) */
  casadi_copy(w15+21, 9, w2);
  /* #166: @38 = dot(@4, @2) */
  w38 = casadi_dot(9, w4, w2);
  /* #167: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #168: (@24[0] += @38) */
  for (rr=w24+0, ss=(&w38); rr!=w24+1; rr+=1) *rr += *ss++;
  /* #169: @3 = (@12*@2) */
  for (i=0, rr=w3, cs=w2; i<9; ++i) (*rr++)  = (w12*(*cs++));
  /* #170: @51 = zeros(3x3) */
  casadi_clear(w51, 9);
  /* #171: @52 = @13' */
  for (i=0, rr=w52, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #172: @51 = mac(@52,@2,@51) */
  for (i=0, rr=w51; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w52+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #173: @3 = (@3+@51) */
  for (i=0, rr=w3, cs=w51; i<9; ++i) (*rr++) += (*cs++);
  /* #174: @51 = zeros(3x3) */
  casadi_clear(w51, 9);
  /* #175: @52 = @4' */
  for (i=0, rr=w52, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #176: @51 = mac(@2,@52,@51) */
  for (i=0, rr=w51; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #177: @51 = (2.*@51) */
  for (i=0, rr=w51, cs=w51; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #178: @3 = (@3+@51) */
  for (i=0, rr=w3, cs=w51; i<9; ++i) (*rr++) += (*cs++);
  /* #179: @12 = @3[5] */
  for (rr=(&w12), ss=w3+5; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #180: (@24[1] += @12) */
  for (rr=w24+1, ss=(&w12); rr!=w24+2; rr+=1) *rr += *ss++;
  /* #181: @12 = 0 */
  w12 = 0.;
  /* #182: (@3[5] = @12) */
  for (rr=w3+5, ss=(&w12); rr!=w3+6; rr+=1) *rr = *ss++;
  /* #183: @12 = @3[2] */
  for (rr=(&w12), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #184: @12 = (-@12) */
  w12 = (- w12 );
  /* #185: (@24[2] += @12) */
  for (rr=w24+2, ss=(&w12); rr!=w24+3; rr+=1) *rr += *ss++;
  /* #186: @12 = 0 */
  w12 = 0.;
  /* #187: (@3[2] = @12) */
  for (rr=w3+2, ss=(&w12); rr!=w3+3; rr+=1) *rr = *ss++;
  /* #188: @12 = @3[1] */
  for (rr=(&w12), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #189: (@24[3] += @12) */
  for (rr=w24+3, ss=(&w12); rr!=w24+4; rr+=1) *rr += *ss++;
  /* #190: @12 = 0 */
  w12 = 0.;
  /* #191: (@3[1] = @12) */
  for (rr=w3+1, ss=(&w12); rr!=w3+2; rr+=1) *rr = *ss++;
  /* #192: @12 = @3[7] */
  for (rr=(&w12), ss=w3+7; ss!=w3+8; ss+=1) *rr++ = *ss;
  /* #193: @12 = (-@12) */
  w12 = (- w12 );
  /* #194: (@24[1] += @12) */
  for (rr=w24+1, ss=(&w12); rr!=w24+2; rr+=1) *rr += *ss++;
  /* #195: @12 = 0 */
  w12 = 0.;
  /* #196: (@3[7] = @12) */
  for (rr=w3+7, ss=(&w12); rr!=w3+8; rr+=1) *rr = *ss++;
  /* #197: @12 = @3[6] */
  for (rr=(&w12), ss=w3+6; ss!=w3+7; ss+=1) *rr++ = *ss;
  /* #198: (@24[2] += @12) */
  for (rr=w24+2, ss=(&w12); rr!=w24+3; rr+=1) *rr += *ss++;
  /* #199: @12 = 0 */
  w12 = 0.;
  /* #200: (@3[6] = @12) */
  for (rr=w3+6, ss=(&w12); rr!=w3+7; rr+=1) *rr = *ss++;
  /* #201: @12 = @3[3] */
  for (rr=(&w12), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #202: @12 = (-@12) */
  w12 = (- w12 );
  /* #203: (@24[3] += @12) */
  for (rr=w24+3, ss=(&w12); rr!=w24+4; rr+=1) *rr += *ss++;
  /* #204: @25 = (@24/@10) */
  for (i=0, rr=w25, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)/w10);
  /* #205: @11 = (@11/@10) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) /= w10;
  /* #206: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #207: @12 = dot(@11, @24) */
  w12 = casadi_dot(4, w11, w24);
  /* #208: @12 = (@12/@10) */
  w12 /= w10;
  /* #209: @9 = (@12*@9) */
  for (i=0, rr=w9, cs=w9; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #210: @25 = (@25+@9) */
  for (i=0, rr=w25, cs=w9; i<4; ++i) (*rr++) += (*cs++);
  /* #211: {@12, @10, @38, @23} = vertsplit(@25) */
  w12 = w25[0];
  w10 = w25[1];
  w38 = w25[2];
  w23 = w25[3];
  /* #212: @39 = (@39+@12) */
  w39 += w12;
  /* #213: output[0][3] = @39 */
  if (res[0]) res[0][3] = w39;
  /* #214: @40 = (@40+@10) */
  w40 += w10;
  /* #215: output[0][4] = @40 */
  if (res[0]) res[0][4] = w40;
  /* #216: @41 = (@41+@38) */
  w41 += w38;
  /* #217: output[0][5] = @41 */
  if (res[0]) res[0][5] = w41;
  /* #218: @42 = (@42+@23) */
  w42 += w23;
  /* #219: output[0][6] = @42 */
  if (res[0]) res[0][6] = w42;
  /* #220: output[0][7] = @43 */
  if (res[0]) res[0][7] = w43;
  /* #221: output[0][8] = @44 */
  if (res[0]) res[0][8] = w44;
  /* #222: output[0][9] = @45 */
  if (res[0]) res[0][9] = w45;
  /* #223: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #224: @34 = @28' */
  for (i=0, rr=w34, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #225: @30 = @35' */
  for (i=0, rr=w30, cs=w35; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #226: {NULL, @28} = horzsplit(@30) */
  casadi_copy(w30+28, 16, w28);
  /* #227: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<16; ++i) *rr++ = (- *cs++ );
  /* #228: @29 = mac(@34,@28,@29) */
  for (i=0, rr=w29; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w34+j, tt=w28+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #229: @45 = 0 */
  w45 = 0.;
  /* #230: (@29[15] = @45) */
  for (rr=w29+15, ss=(&w45); rr!=w29+16; rr+=1) *rr = *ss++;
  /* #231: @45 = 0 */
  w45 = 0.;
  /* #232: (@29[11] = @45) */
  for (rr=w29+11, ss=(&w45); rr!=w29+12; rr+=1) *rr = *ss++;
  /* #233: @45 = 0 */
  w45 = 0.;
  /* #234: (@29[7] = @45) */
  for (rr=w29+7, ss=(&w45); rr!=w29+8; rr+=1) *rr = *ss++;
  /* #235: @45 = 0 */
  w45 = 0.;
  /* #236: (@29[3] = @45) */
  for (rr=w29+3, ss=(&w45); rr!=w29+4; rr+=1) *rr = *ss++;
  /* #237: @45 = 0 */
  w45 = 0.;
  /* #238: (@29[14] = @45) */
  for (rr=w29+14, ss=(&w45); rr!=w29+15; rr+=1) *rr = *ss++;
  /* #239: @45 = 0 */
  w45 = 0.;
  /* #240: (@29[10] = @45) */
  for (rr=w29+10, ss=(&w45); rr!=w29+11; rr+=1) *rr = *ss++;
  /* #241: @45 = 0 */
  w45 = 0.;
  /* #242: (@29[6] = @45) */
  for (rr=w29+6, ss=(&w45); rr!=w29+7; rr+=1) *rr = *ss++;
  /* #243: @45 = 0 */
  w45 = 0.;
  /* #244: (@29[2] = @45) */
  for (rr=w29+2, ss=(&w45); rr!=w29+3; rr+=1) *rr = *ss++;
  /* #245: @45 = 0 */
  w45 = 0.;
  /* #246: (@29[13] = @45) */
  for (rr=w29+13, ss=(&w45); rr!=w29+14; rr+=1) *rr = *ss++;
  /* #247: @45 = 0 */
  w45 = 0.;
  /* #248: (@29[9] = @45) */
  for (rr=w29+9, ss=(&w45); rr!=w29+10; rr+=1) *rr = *ss++;
  /* #249: @45 = 0 */
  w45 = 0.;
  /* #250: (@29[5] = @45) */
  for (rr=w29+5, ss=(&w45); rr!=w29+6; rr+=1) *rr = *ss++;
  /* #251: @45 = @29[1] */
  for (rr=(&w45), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #252: @20 = (@20*@45) */
  w20 *= w45;
  /* #253: @46 = (@46+@20) */
  w46 += w20;
  /* #254: @20 = 0 */
  w20 = 0.;
  /* #255: (@29[1] = @20) */
  for (rr=w29+1, ss=(&w20); rr!=w29+2; rr+=1) *rr = *ss++;
  /* #256: @20 = 0 */
  w20 = 0.;
  /* #257: (@29[12] = @20) */
  for (rr=w29+12, ss=(&w20); rr!=w29+13; rr+=1) *rr = *ss++;
  /* #258: @20 = 0 */
  w20 = 0.;
  /* #259: (@29[8] = @20) */
  for (rr=w29+8, ss=(&w20); rr!=w29+9; rr+=1) *rr = *ss++;
  /* #260: @20 = @29[4] */
  for (rr=(&w20), ss=w29+4; ss!=w29+5; ss+=1) *rr++ = *ss;
  /* #261: @19 = (@19*@20) */
  w19 *= w20;
  /* #262: @46 = (@46+@19) */
  w46 += w19;
  /* #263: @30 = @31' */
  for (i=0, rr=w30, cs=w31; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #264: {NULL, @29, NULL} = horzsplit(@30) */
  casadi_copy(w30+12, 16, w29);
  /* #265: @29 = (@18*@29) */
  for (i=0, rr=w29, cs=w29; i<16; ++i) (*rr++)  = (w18*(*cs++));
  /* #266: @34 = @29' */
  for (i=0, rr=w34, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #267: {@25, @9, @11, @24} = horzsplit(@34) */
  casadi_copy(w34, 4, w25);
  casadi_copy(w34+4, 4, w9);
  casadi_copy(w34+8, 4, w11);
  casadi_copy(w34+12, 4, w24);
  /* #268: @24 = @24' */
  /* #269: {@18, NULL, NULL, NULL} = horzsplit(@24) */
  w18 = w24[0];
  /* #270: @46 = (@46+@18) */
  w46 += w18;
  /* #271: @11 = @11' */
  /* #272: {NULL, @18, NULL, NULL} = horzsplit(@11) */
  w18 = w11[1];
  /* #273: @46 = (@46-@18) */
  w46 -= w18;
  /* #274: @9 = @9' */
  /* #275: {NULL, NULL, @18, NULL} = horzsplit(@9) */
  w18 = w9[2];
  /* #276: @46 = (@46+@18) */
  w46 += w18;
  /* #277: @25 = @25' */
  /* #278: {NULL, NULL, NULL, @18} = horzsplit(@25) */
  w18 = w25[3];
  /* #279: @46 = (@46-@18) */
  w46 -= w18;
  /* #280: output[0][10] = @46 */
  if (res[0]) res[0][10] = w46;
  /* #281: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #282: @32 = zeros(4x7) */
  casadi_clear(w32, 28);
  /* #283: @34 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w34);
  /* #284: @34 = (@33\@34) */
  rr = w34;
  ss = w33;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #285: @33 = @34' */
  for (i=0, rr=w33, cs=w34; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #286: @30 = horzcat(@32, @33) */
  rr=w30;
  for (i=0, cs=w32; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<16; ++i) *rr++ = *cs++;
  /* #287: @25 = mac(@30,@37,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w30+j, tt=w37+i*11; k<11; ++k) *rr += ss[k*4]**tt++;
  /* #288: {@46, @18, @19, @20} = vertsplit(@25) */
  w46 = w25[0];
  w18 = w25[1];
  w19 = w25[2];
  w20 = w25[3];
  /* #289: output[0][11] = @46 */
  if (res[0]) res[0][11] = w46;
  /* #290: output[0][12] = @18 */
  if (res[0]) res[0][12] = w18;
  /* #291: output[0][13] = @19 */
  if (res[0]) res[0][13] = w19;
  /* #292: output[0][14] = @20 */
  if (res[0]) res[0][14] = w20;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 703;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
