/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s5[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s6[27] = {8, 8, 0, 4, 8, 12, 16, 16, 16, 16, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s7[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s10[11] = {0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_e_fun_jac_hess:(i0[8],i1[],i2[],i3[8])->(o0,o1[8],o2[8x8,16nz],o3[],o4[0x8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, *w10=w+14, *w11=w+22, *w12=w+26, *w13=w+30, *w14=w+46, *w15=w+62, *w16=w+78;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9) */
  rr=w10;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #11: @11 = @10[:4] */
  for (rr=w11, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #12: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #13: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #14: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #15: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #16: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #17: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #18: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #19: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #20: @10 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9) */
  rr=w10;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #21: @12 = @10[:4] */
  for (rr=w12, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #22: @11 = (@11-@12) */
  for (i=0, rr=w11, cs=w12; i<4; ++i) (*rr++) -= (*cs++);
  /* #23: @12 = @11' */
  casadi_copy(w11, 4, w12);
  /* #24: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #25: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #26: (@13[0] = @2) */
  for (rr=w13+0, ss=(&w2); rr!=w13+1; rr+=1) *rr = *ss++;
  /* #27: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #28: (@13[5] = @2) */
  for (rr=w13+5, ss=(&w2); rr!=w13+6; rr+=1) *rr = *ss++;
  /* #29: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #30: (@13[10] = @2) */
  for (rr=w13+10, ss=(&w2); rr!=w13+11; rr+=1) *rr = *ss++;
  /* #31: @2 = 1 */
  w2 = 1.;
  /* #32: (@13[15] = @2) */
  for (rr=w13+15, ss=(&w2); rr!=w13+16; rr+=1) *rr = *ss++;
  /* #33: @1 = mac(@12,@13,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #34: @0 = mac(@1,@11,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w11+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #35: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #36: @10 = zeros(8x1) */
  casadi_clear(w10, 8);
  /* #37: @1 = @1' */
  /* #38: @12 = zeros(1x4) */
  casadi_clear(w12, 4);
  /* #39: @11 = @11' */
  /* #40: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #41: @12 = mac(@11,@14,@12) */
  for (i=0, rr=w12; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w11+j, tt=w14+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #42: @12 = @12' */
  /* #43: @1 = (@1+@12) */
  for (i=0, rr=w1, cs=w12; i<4; ++i) (*rr++) += (*cs++);
  /* #44: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #45: (@10[:4] += @1) */
  for (rr=w10+0, ss=w1; rr!=w10+4; rr+=1) *rr += *ss++;
  /* #46: output[1][0] = @10 */
  casadi_copy(w10, 8, res[1]);
  /* #47: @15 = zeros(8x8,16nz) */
  casadi_clear(w15, 16);
  /* #48: @10 = zeros(8x1) */
  casadi_clear(w10, 8);
  /* #49: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #50: @16 = ones(8x1,5nz) */
  casadi_fill(w16, 5, 1.);
  /* #51: {@0, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@16) */
  w0 = w16[0];
  /* #52: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #53: @2 = (-@2) */
  w2 = (- w2 );
  /* #54: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #55: @1 = mac(@0,@13,@1) */
  casadi_mtimes((&w0), casadi_s2, w13, casadi_s1, w1, casadi_s0, w, 0);
  /* #56: @1 = @1' */
  /* #57: @12 = zeros(1x4) */
  casadi_clear(w12, 4);
  /* #58: @2 = @2' */
  /* #59: @12 = mac(@2,@14,@12) */
  casadi_mtimes((&w2), casadi_s2, w14, casadi_s1, w12, casadi_s0, w, 0);
  /* #60: @12 = @12' */
  /* #61: @1 = (@1+@12) */
  for (i=0, rr=w1, cs=w12; i<4; ++i) (*rr++) += (*cs++);
  /* #62: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #63: (@10[:4] += @1) */
  for (rr=w10+0, ss=w1; rr!=w10+4; rr+=1) *rr += *ss++;
  /* #64: @1 = @10[:4] */
  for (rr=w1, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #65: (@15[:4] = @1) */
  for (rr=w15+0, ss=w1; rr!=w15+4; rr+=1) *rr = *ss++;
  /* #66: @1 = @10[:4] */
  for (rr=w1, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #67: (@15[:16:4] = @1) */
  for (rr=w15+0, ss=w1; rr!=w15+16; rr+=4) *rr = *ss++;
  /* #68: @10 = zeros(8x1) */
  casadi_clear(w10, 8);
  /* #69: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #70: @2 = ones(8x1,1nz) */
  w2 = 1.;
  /* #71: {NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #72: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #73: @2 = (-@2) */
  w2 = (- w2 );
  /* #74: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #75: @1 = mac(@0,@13,@1) */
  casadi_mtimes((&w0), casadi_s3, w13, casadi_s1, w1, casadi_s0, w, 0);
  /* #76: @1 = @1' */
  /* #77: @12 = zeros(1x4) */
  casadi_clear(w12, 4);
  /* #78: @2 = @2' */
  /* #79: @12 = mac(@2,@14,@12) */
  casadi_mtimes((&w2), casadi_s3, w14, casadi_s1, w12, casadi_s0, w, 0);
  /* #80: @12 = @12' */
  /* #81: @1 = (@1+@12) */
  for (i=0, rr=w1, cs=w12; i<4; ++i) (*rr++) += (*cs++);
  /* #82: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #83: (@10[:4] += @1) */
  for (rr=w10+0, ss=w1; rr!=w10+4; rr+=1) *rr += *ss++;
  /* #84: @1 = @10[:4] */
  for (rr=w1, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #85: (@15[4:8] = @1) */
  for (rr=w15+4, ss=w1; rr!=w15+8; rr+=1) *rr = *ss++;
  /* #86: @1 = @10[:4] */
  for (rr=w1, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #87: (@15[1:17:4] = @1) */
  for (rr=w15+1, ss=w1; rr!=w15+17; rr+=4) *rr = *ss++;
  /* #88: @10 = zeros(8x1) */
  casadi_clear(w10, 8);
  /* #89: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #90: @2 = ones(8x1,1nz) */
  w2 = 1.;
  /* #91: {NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #92: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #93: @2 = (-@2) */
  w2 = (- w2 );
  /* #94: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #95: @1 = mac(@0,@13,@1) */
  casadi_mtimes((&w0), casadi_s4, w13, casadi_s1, w1, casadi_s0, w, 0);
  /* #96: @1 = @1' */
  /* #97: @12 = zeros(1x4) */
  casadi_clear(w12, 4);
  /* #98: @2 = @2' */
  /* #99: @12 = mac(@2,@14,@12) */
  casadi_mtimes((&w2), casadi_s4, w14, casadi_s1, w12, casadi_s0, w, 0);
  /* #100: @12 = @12' */
  /* #101: @1 = (@1+@12) */
  for (i=0, rr=w1, cs=w12; i<4; ++i) (*rr++) += (*cs++);
  /* #102: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #103: (@10[:4] += @1) */
  for (rr=w10+0, ss=w1; rr!=w10+4; rr+=1) *rr += *ss++;
  /* #104: @1 = @10[:4] */
  for (rr=w1, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #105: (@15[8:12] = @1) */
  for (rr=w15+8, ss=w1; rr!=w15+12; rr+=1) *rr = *ss++;
  /* #106: @1 = @10[:4] */
  for (rr=w1, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #107: (@15[2:18:4] = @1) */
  for (rr=w15+2, ss=w1; rr!=w15+18; rr+=4) *rr = *ss++;
  /* #108: @10 = zeros(8x1) */
  casadi_clear(w10, 8);
  /* #109: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #110: @2 = ones(8x1,1nz) */
  w2 = 1.;
  /* #111: {NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #112: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #113: @2 = (-@2) */
  w2 = (- w2 );
  /* #114: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #115: @1 = mac(@0,@13,@1) */
  casadi_mtimes((&w0), casadi_s5, w13, casadi_s1, w1, casadi_s0, w, 0);
  /* #116: @1 = @1' */
  /* #117: @12 = zeros(1x4) */
  casadi_clear(w12, 4);
  /* #118: @2 = @2' */
  /* #119: @12 = mac(@2,@14,@12) */
  casadi_mtimes((&w2), casadi_s5, w14, casadi_s1, w12, casadi_s0, w, 0);
  /* #120: @12 = @12' */
  /* #121: @1 = (@1+@12) */
  for (i=0, rr=w1, cs=w12; i<4; ++i) (*rr++) += (*cs++);
  /* #122: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #123: (@10[:4] += @1) */
  for (rr=w10+0, ss=w1; rr!=w10+4; rr+=1) *rr += *ss++;
  /* #124: @1 = @10[:4] */
  for (rr=w1, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #125: (@15[12:16] = @1) */
  for (rr=w15+12, ss=w1; rr!=w15+16; rr+=1) *rr = *ss++;
  /* #126: @1 = @10[:4] */
  for (rr=w1, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #127: (@15[3:19:4] = @1) */
  for (rr=w15+3, ss=w1; rr!=w15+19; rr+=4) *rr = *ss++;
  /* #128: @14 = @15' */
  casadi_trans(w15,casadi_s6, w14, casadi_s6, iw);
  /* #129: output[2][0] = @14 */
  casadi_copy(w14, 16, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s8;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s7;
    case 2: return casadi_s6;
    case 3: return casadi_s8;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 83;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
