/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[11] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28};
static const casadi_int casadi_s7[11] = {0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37};
static const casadi_int casadi_s8[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s9[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s10[11] = {4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32};
static const casadi_int casadi_s11[11] = {1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38};
static const casadi_int casadi_s12[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s14[11] = {8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36};
static const casadi_int casadi_s15[11] = {2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39};
static const casadi_int casadi_s16[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[59] = {15, 15, 0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37, 41, 41, 41, 41, 41, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 7, 8, 9, 10, 7, 8, 9, 10, 7, 8, 9, 10, 7, 8, 9, 10};
static const casadi_int casadi_s18[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s19[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s20[3] = {0, 0, 0};
static const casadi_int casadi_s21[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s22[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s23[18] = {0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_fun_jac_hess:(i0[11],i1[4],i2[],i3[15])->(o0,o1[15],o2[15x15,41nz],o3[],o4[0x15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w19=w+38, *w20=w+49, *w21=w+52, *w22=w+61, *w23=w+65, *w24=w+69, *w25=w+73, *w26=w+89, *w27=w+93, *w28=w+96, *w29=w+112, *w30=w+115, w31, w32, w33, *w34=w+127, *w35=w+168, w39, w40, w41, w42, w43, w44, w45, *w46=w+182, *w51=w+184, *w52=w+192, *w53=w+200;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, ss=w17+0; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #19: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #20: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #21: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #22: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #23: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #24: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #25: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #26: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #27: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #28: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #29: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #30: @19 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #31: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #32: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #34: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #35: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #36: (@21[0] = @2) */
  for (rr=w21+0, ss=(&w2); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #38: (@21[4] = @2) */
  for (rr=w21+4, ss=(&w2); rr!=w21+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #40: (@21[8] = @2) */
  for (rr=w21+8, ss=(&w2); rr!=w21+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@20,@21,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@18,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: @2 = 0 */
  w2 = 0.;
  /* #44: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #45: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #46: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #47: @13 = input[1][2] */
  w13 = arg[1] ? arg[1][2] : 0;
  /* #48: @14 = input[1][3] */
  w14 = arg[1] ? arg[1][3] : 0;
  /* #49: @23 = vertcat(@3, @4, @13, @14) */
  rr=w23;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w13;
  *rr++ = w14;
  /* #50: @24 = @23' */
  casadi_copy(w23, 4, w24);
  /* #51: @25 = zeros(4x4) */
  casadi_clear(w25, 16);
  /* #52: @3 = 1 */
  w3 = 1.;
  /* #53: (@25[0] = @3) */
  for (rr=w25+0, ss=(&w3); rr!=w25+1; rr+=1) *rr = *ss++;
  /* #54: @3 = 1 */
  w3 = 1.;
  /* #55: (@25[5] = @3) */
  for (rr=w25+5, ss=(&w3); rr!=w25+6; rr+=1) *rr = *ss++;
  /* #56: @3 = 1 */
  w3 = 1.;
  /* #57: (@25[10] = @3) */
  for (rr=w25+10, ss=(&w3); rr!=w25+11; rr+=1) *rr = *ss++;
  /* #58: @3 = 1 */
  w3 = 1.;
  /* #59: (@25[15] = @3) */
  for (rr=w25+15, ss=(&w3); rr!=w25+16; rr+=1) *rr = *ss++;
  /* #60: @22 = mac(@24,@25,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #61: @2 = mac(@22,@23,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #62: @0 = (@0+@2) */
  w0 += w2;
  /* #63: @2 = 1 */
  w2 = 1.;
  /* #64: @6 = (-@6) */
  w6 = (- w6 );
  /* #65: @7 = (-@7) */
  w7 = (- w7 );
  /* #66: @8 = (-@8) */
  w8 = (- w8 );
  /* #67: @24 = vertcat(@5, @6, @7, @8) */
  rr=w24;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #68: @26 = @17[3:7] */
  for (rr=w26, ss=w17+3; ss!=w17+7; ss+=1) *rr++ = *ss;
  /* #69: @5 = ||@26||_F */
  w5 = sqrt(casadi_dot(4, w26, w26));
  /* #70: @24 = (@24/@5) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w5;
  /* #71: @5 = @24[0] */
  for (rr=(&w5), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #72: @6 = (@5*@9) */
  w6  = (w5*w9);
  /* #73: @7 = @24[1] */
  for (rr=(&w7), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #74: @8 = (@7*@10) */
  w8  = (w7*w10);
  /* #75: @6 = (@6-@8) */
  w6 -= w8;
  /* #76: @8 = @24[2] */
  for (rr=(&w8), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #77: @3 = (@8*@11) */
  w3  = (w8*w11);
  /* #78: @6 = (@6-@3) */
  w6 -= w3;
  /* #79: @3 = @24[3] */
  for (rr=(&w3), ss=w24+3; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #80: @4 = (@3*@12) */
  w4  = (w3*w12);
  /* #81: @6 = (@6-@4) */
  w6 -= w4;
  /* #82: @2 = (@2-@6) */
  w2 -= w6;
  /* #83: @0 = (@0+@2) */
  w0 += w2;
  /* #84: @2 = 0 */
  w2 = 0.;
  /* #85: @4 = 7 */
  w4 = 7.;
  /* #86: @13 = (@5*@10) */
  w13  = (w5*w10);
  /* #87: @14 = (@7*@9) */
  w14  = (w7*w9);
  /* #88: @13 = (@13+@14) */
  w13 += w14;
  /* #89: @14 = (@8*@12) */
  w14  = (w8*w12);
  /* #90: @13 = (@13+@14) */
  w13 += w14;
  /* #91: @14 = (@3*@11) */
  w14  = (w3*w11);
  /* #92: @13 = (@13-@14) */
  w13 -= w14;
  /* #93: @14 = (@5*@11) */
  w14  = (w5*w11);
  /* #94: @15 = (@7*@12) */
  w15  = (w7*w12);
  /* #95: @14 = (@14-@15) */
  w14 -= w15;
  /* #96: @15 = (@8*@9) */
  w15  = (w8*w9);
  /* #97: @14 = (@14+@15) */
  w14 += w15;
  /* #98: @15 = (@3*@10) */
  w15  = (w3*w10);
  /* #99: @14 = (@14+@15) */
  w14 += w15;
  /* #100: @12 = (@5*@12) */
  w12  = (w5*w12);
  /* #101: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #102: @12 = (@12+@11) */
  w12 += w11;
  /* #103: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #104: @12 = (@12-@10) */
  w12 -= w10;
  /* #105: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #106: @12 = (@12+@9) */
  w12 += w9;
  /* #107: @24 = vertcat(@6, @13, @14, @12) */
  rr=w24;
  *rr++ = w6;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w12;
  /* #108: @20 = @24[1:4] */
  for (rr=w20, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #109: @20 = @20' */
  /* #110: @20 = (@4*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #111: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #112: @2 = mac(@20,@27,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #113: @0 = (@0+@2) */
  w0 += w2;
  /* #114: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #115: @22 = @22' */
  /* #116: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #117: @23 = @23' */
  /* #118: @28 = @25' */
  for (i=0, rr=w28, cs=w25; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #119: @24 = mac(@23,@28,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w28+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #120: @24 = @24' */
  /* #121: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #122: {@0, @2, @6, @13} = vertsplit(@22) */
  w0 = w22[0];
  w2 = w22[1];
  w6 = w22[2];
  w13 = w22[3];
  /* #123: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #124: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #125: output[1][2] = @6 */
  if (res[1]) res[1][2] = w6;
  /* #126: output[1][3] = @13 */
  if (res[1]) res[1][3] = w13;
  /* #127: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #128: @1 = @1' */
  /* #129: @29 = zeros(1x3) */
  casadi_clear(w29, 3);
  /* #130: @18 = @18' */
  /* #131: @30 = @21' */
  for (i=0, rr=w30, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #132: @29 = mac(@18,@30,@29) */
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #133: @29 = @29' */
  /* #134: @1 = (@1+@29) */
  for (i=0, rr=w1, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #135: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #136: (@19[:3] += @1) */
  for (rr=w19+0, ss=w1; rr!=w19+3; rr+=1) *rr += *ss++;
  /* #137: {@13, @6, @2, @0, @14, @12, @9, @10, @11, @15, @16} = vertsplit(@19) */
  w13 = w19[0];
  w6 = w19[1];
  w2 = w19[2];
  w0 = w19[3];
  w14 = w19[4];
  w12 = w19[5];
  w9 = w19[6];
  w10 = w19[7];
  w11 = w19[8];
  w15 = w19[9];
  w16 = w19[10];
  /* #138: output[1][4] = @13 */
  if (res[1]) res[1][4] = w13;
  /* #139: output[1][5] = @6 */
  if (res[1]) res[1][5] = w6;
  /* #140: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #141: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #142: @20 = @20' */
  /* #143: (@22[1:4] += @20) */
  for (rr=w22+1, ss=w20; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #144: @27 = @27' */
  /* #145: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #146: @27 = @27' */
  /* #147: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #148: {@2, @6, @13, @31} = vertsplit(@22) */
  w2 = w22[0];
  w6 = w22[1];
  w13 = w22[2];
  w31 = w22[3];
  /* #149: @32 = (@3*@31) */
  w32  = (w3*w31);
  /* #150: @33 = (@8*@13) */
  w33  = (w8*w13);
  /* #151: @32 = (@32+@33) */
  w32 += w33;
  /* #152: @33 = (@7*@6) */
  w33  = (w7*w6);
  /* #153: @32 = (@32+@33) */
  w32 += w33;
  /* #154: @33 = -1 */
  w33 = -1.;
  /* #155: @33 = (@33+@2) */
  w33 += w2;
  /* #156: @2 = (@5*@33) */
  w2  = (w5*w33);
  /* #157: @32 = (@32+@2) */
  w32 += w2;
  /* #158: @32 = (@32+@0) */
  w32 += w0;
  /* #159: output[1][7] = @32 */
  if (res[1]) res[1][7] = w32;
  /* #160: @32 = (@3*@13) */
  w32  = (w3*w13);
  /* #161: @0 = (@8*@31) */
  w0  = (w8*w31);
  /* #162: @32 = (@32-@0) */
  w32 -= w0;
  /* #163: @0 = (@5*@6) */
  w0  = (w5*w6);
  /* #164: @32 = (@32+@0) */
  w32 += w0;
  /* #165: @0 = (@7*@33) */
  w0  = (w7*w33);
  /* #166: @32 = (@32-@0) */
  w32 -= w0;
  /* #167: @32 = (@32+@14) */
  w32 += w14;
  /* #168: output[1][8] = @32 */
  if (res[1]) res[1][8] = w32;
  /* #169: @32 = (@7*@31) */
  w32  = (w7*w31);
  /* #170: @14 = (@5*@13) */
  w14  = (w5*w13);
  /* #171: @32 = (@32+@14) */
  w32 += w14;
  /* #172: @14 = (@3*@6) */
  w14  = (w3*w6);
  /* #173: @32 = (@32-@14) */
  w32 -= w14;
  /* #174: @14 = (@8*@33) */
  w14  = (w8*w33);
  /* #175: @32 = (@32-@14) */
  w32 -= w14;
  /* #176: @32 = (@32+@12) */
  w32 += w12;
  /* #177: output[1][9] = @32 */
  if (res[1]) res[1][9] = w32;
  /* #178: @31 = (@5*@31) */
  w31  = (w5*w31);
  /* #179: @13 = (@7*@13) */
  w13  = (w7*w13);
  /* #180: @31 = (@31-@13) */
  w31 -= w13;
  /* #181: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #182: @31 = (@31+@6) */
  w31 += w6;
  /* #183: @33 = (@3*@33) */
  w33  = (w3*w33);
  /* #184: @31 = (@31-@33) */
  w31 -= w33;
  /* #185: @31 = (@31+@9) */
  w31 += w9;
  /* #186: output[1][10] = @31 */
  if (res[1]) res[1][10] = w31;
  /* #187: output[1][11] = @10 */
  if (res[1]) res[1][11] = w10;
  /* #188: output[1][12] = @11 */
  if (res[1]) res[1][12] = w11;
  /* #189: output[1][13] = @15 */
  if (res[1]) res[1][13] = w15;
  /* #190: output[1][14] = @16 */
  if (res[1]) res[1][14] = w16;
  /* #191: @34 = zeros(15x15,41nz) */
  casadi_clear(w34, 41);
  /* #192: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #193: @35 = ones(15x1,7nz) */
  casadi_fill(w35, 7, 1.);
  /* #194: {@16, NULL, NULL, NULL, @15, NULL, NULL, @11, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@35) */
  w16 = w35[0];
  w15 = w35[1];
  w11 = w35[2];
  /* #195: @36 = 00 */
  /* #196: @37 = 00 */
  /* #197: @38 = 00 */
  /* #198: @10 = vertcat(@16, @36, @37, @38) */
  rr=(&w10);
  *rr++ = w16;
  /* #199: @16 = @10' */
  casadi_copy((&w10), 1, (&w16));
  /* #200: @22 = mac(@16,@25,@22) */
  casadi_mtimes((&w16), casadi_s2, w25, casadi_s1, w22, casadi_s0, w, 0);
  /* #201: @22 = @22' */
  /* #202: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #203: @10 = @10' */
  /* #204: @24 = mac(@10,@28,@24) */
  casadi_mtimes((&w10), casadi_s2, w28, casadi_s1, w24, casadi_s0, w, 0);
  /* #205: @24 = @24' */
  /* #206: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #207: {@10, @16, @31, @9} = vertsplit(@22) */
  w10 = w22[0];
  w16 = w22[1];
  w31 = w22[2];
  w9 = w22[3];
  /* #208: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #209: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #210: @33 = @15[0] */
  for (rr=(&w33), ss=(&w15)+0; ss!=(&w15)+1; ss+=1) *rr++ = *ss;
  /* #211: @33 = (-@33) */
  w33 = (- w33 );
  /* #212: @15 = @33' */
  casadi_copy((&w33), 1, (&w15));
  /* #213: @27 = mac(@15,@21,@27) */
  casadi_mtimes((&w15), casadi_s5, w21, casadi_s4, w27, casadi_s3, w, 0);
  /* #214: @27 = @27' */
  /* #215: @20 = zeros(1x3) */
  casadi_clear(w20, 3);
  /* #216: @33 = @33' */
  /* #217: @20 = mac(@33,@30,@20) */
  casadi_mtimes((&w33), casadi_s5, w30, casadi_s4, w20, casadi_s3, w, 0);
  /* #218: @20 = @20' */
  /* #219: @27 = (@27+@20) */
  for (i=0, rr=w27, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #220: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #221: (@19[:3] += @27) */
  for (rr=w19+0, ss=w27; rr!=w19+3; rr+=1) *rr += *ss++;
  /* #222: {@33, @15, @6, @13, @32, @12, @14, @0, @2, @39, @40} = vertsplit(@19) */
  w33 = w19[0];
  w15 = w19[1];
  w6 = w19[2];
  w13 = w19[3];
  w32 = w19[4];
  w12 = w19[5];
  w14 = w19[6];
  w0 = w19[7];
  w2 = w19[8];
  w39 = w19[9];
  w40 = w19[10];
  /* #223: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #224: @41 = (@5*@11) */
  w41  = (w5*w11);
  /* #225: @42 = (@7*@11) */
  w42  = (w7*w11);
  /* #226: @43 = (@8*@11) */
  w43  = (w8*w11);
  /* #227: @11 = (@3*@11) */
  w11  = (w3*w11);
  /* #228: @24 = vertcat(@41, @42, @43, @11) */
  rr=w24;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w11;
  /* #229: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #230: @27 = @27' */
  /* #231: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #232: @27 = @27' */
  /* #233: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #234: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #235: @27 = @27' */
  /* #236: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #237: @27 = @27' */
  /* #238: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #239: {@41, @42, @43, @11} = vertsplit(@22) */
  w41 = w22[0];
  w42 = w22[1];
  w43 = w22[2];
  w11 = w22[3];
  /* #240: @44 = (@3*@11) */
  w44  = (w3*w11);
  /* #241: @45 = (@8*@43) */
  w45  = (w8*w43);
  /* #242: @44 = (@44+@45) */
  w44 += w45;
  /* #243: @45 = (@7*@42) */
  w45  = (w7*w42);
  /* #244: @44 = (@44+@45) */
  w44 += w45;
  /* #245: @45 = (@5*@41) */
  w45  = (w5*w41);
  /* #246: @44 = (@44+@45) */
  w44 += w45;
  /* #247: @44 = (@44+@13) */
  w44 += w13;
  /* #248: @13 = (@3*@43) */
  w13  = (w3*w43);
  /* #249: @45 = (@8*@11) */
  w45  = (w8*w11);
  /* #250: @13 = (@13-@45) */
  w13 -= w45;
  /* #251: @45 = (@5*@42) */
  w45  = (w5*w42);
  /* #252: @13 = (@13+@45) */
  w13 += w45;
  /* #253: @45 = (@7*@41) */
  w45  = (w7*w41);
  /* #254: @13 = (@13-@45) */
  w13 -= w45;
  /* #255: @13 = (@13+@32) */
  w13 += w32;
  /* #256: @32 = (@7*@11) */
  w32  = (w7*w11);
  /* #257: @45 = (@5*@43) */
  w45  = (w5*w43);
  /* #258: @32 = (@32+@45) */
  w32 += w45;
  /* #259: @45 = (@3*@42) */
  w45  = (w3*w42);
  /* #260: @32 = (@32-@45) */
  w32 -= w45;
  /* #261: @45 = (@8*@41) */
  w45  = (w8*w41);
  /* #262: @32 = (@32-@45) */
  w32 -= w45;
  /* #263: @32 = (@32+@12) */
  w32 += w12;
  /* #264: @11 = (@5*@11) */
  w11  = (w5*w11);
  /* #265: @43 = (@7*@43) */
  w43  = (w7*w43);
  /* #266: @11 = (@11-@43) */
  w11 -= w43;
  /* #267: @42 = (@8*@42) */
  w42  = (w8*w42);
  /* #268: @11 = (@11+@42) */
  w11 += w42;
  /* #269: @41 = (@3*@41) */
  w41  = (w3*w41);
  /* #270: @11 = (@11-@41) */
  w11 -= w41;
  /* #271: @11 = (@11+@14) */
  w11 += w14;
  /* #272: @17 = vertcat(@10, @16, @31, @9, @33, @15, @6, @44, @13, @32, @11, @0, @2, @39, @40) */
  rr=w17;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w31;
  *rr++ = w9;
  *rr++ = w33;
  *rr++ = w15;
  *rr++ = w6;
  *rr++ = w44;
  *rr++ = w13;
  *rr++ = w32;
  *rr++ = w11;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w39;
  *rr++ = w40;
  /* #273: @19 = @17[:11] */
  for (rr=w19, ss=w17+0; ss!=w17+11; ss+=1) *rr++ = *ss;
  /* #274: (@34[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @19) */
  for (cii=casadi_s6, rr=w34, ss=w19; cii!=casadi_s6+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #275: @19 = @17[:11] */
  for (rr=w19, ss=w17+0; ss!=w17+11; ss+=1) *rr++ = *ss;
  /* #276: (@34[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @19) */
  for (cii=casadi_s7, rr=w34, ss=w19; cii!=casadi_s7+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #277: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #278: @36 = 00 */
  /* #279: @27 = ones(15x1,3nz) */
  casadi_fill(w27, 3, 1.);
  /* #280: {NULL, @10, NULL, NULL, NULL, @16, NULL, NULL, @31, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@27) */
  w10 = w27[0];
  w16 = w27[1];
  w31 = w27[2];
  /* #281: @37 = 00 */
  /* #282: @38 = 00 */
  /* #283: @9 = vertcat(@36, @10, @37, @38) */
  rr=(&w9);
  *rr++ = w10;
  /* #284: @10 = @9' */
  casadi_copy((&w9), 1, (&w10));
  /* #285: @22 = mac(@10,@25,@22) */
  casadi_mtimes((&w10), casadi_s8, w25, casadi_s1, w22, casadi_s0, w, 0);
  /* #286: @22 = @22' */
  /* #287: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #288: @9 = @9' */
  /* #289: @24 = mac(@9,@28,@24) */
  casadi_mtimes((&w9), casadi_s8, w28, casadi_s1, w24, casadi_s0, w, 0);
  /* #290: @24 = @24' */
  /* #291: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #292: {@9, @10, @33, @15} = vertsplit(@22) */
  w9 = w22[0];
  w10 = w22[1];
  w33 = w22[2];
  w15 = w22[3];
  /* #293: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #294: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #295: @6 = @16[0] */
  for (rr=(&w6), ss=(&w16)+0; ss!=(&w16)+1; ss+=1) *rr++ = *ss;
  /* #296: @6 = (-@6) */
  w6 = (- w6 );
  /* #297: @16 = @6' */
  casadi_copy((&w6), 1, (&w16));
  /* #298: @27 = mac(@16,@21,@27) */
  casadi_mtimes((&w16), casadi_s9, w21, casadi_s4, w27, casadi_s3, w, 0);
  /* #299: @27 = @27' */
  /* #300: @20 = zeros(1x3) */
  casadi_clear(w20, 3);
  /* #301: @6 = @6' */
  /* #302: @20 = mac(@6,@30,@20) */
  casadi_mtimes((&w6), casadi_s9, w30, casadi_s4, w20, casadi_s3, w, 0);
  /* #303: @20 = @20' */
  /* #304: @27 = (@27+@20) */
  for (i=0, rr=w27, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #305: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #306: (@19[:3] += @27) */
  for (rr=w19+0, ss=w27; rr!=w19+3; rr+=1) *rr += *ss++;
  /* #307: {@6, @16, @44, @13, @32, @11, @0, @2, @39, @40, @14} = vertsplit(@19) */
  w6 = w19[0];
  w16 = w19[1];
  w44 = w19[2];
  w13 = w19[3];
  w32 = w19[4];
  w11 = w19[5];
  w0 = w19[6];
  w2 = w19[7];
  w39 = w19[8];
  w40 = w19[9];
  w14 = w19[10];
  /* #308: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #309: @41 = (@7*@31) */
  w41  = (w7*w31);
  /* #310: @41 = (-@41) */
  w41 = (- w41 );
  /* #311: @42 = (@5*@31) */
  w42  = (w5*w31);
  /* #312: @43 = (@3*@31) */
  w43  = (w3*w31);
  /* #313: @31 = (@8*@31) */
  w31  = (w8*w31);
  /* #314: @31 = (-@31) */
  w31 = (- w31 );
  /* #315: @24 = vertcat(@41, @42, @43, @31) */
  rr=w24;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w31;
  /* #316: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #317: @27 = @27' */
  /* #318: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #319: @27 = @27' */
  /* #320: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #321: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #322: @27 = @27' */
  /* #323: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #324: @27 = @27' */
  /* #325: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #326: {@41, @42, @43, @31} = vertsplit(@22) */
  w41 = w22[0];
  w42 = w22[1];
  w43 = w22[2];
  w31 = w22[3];
  /* #327: @12 = (@3*@31) */
  w12  = (w3*w31);
  /* #328: @45 = (@8*@43) */
  w45  = (w8*w43);
  /* #329: @12 = (@12+@45) */
  w12 += w45;
  /* #330: @45 = (@7*@42) */
  w45  = (w7*w42);
  /* #331: @12 = (@12+@45) */
  w12 += w45;
  /* #332: @45 = (@5*@41) */
  w45  = (w5*w41);
  /* #333: @12 = (@12+@45) */
  w12 += w45;
  /* #334: @12 = (@12+@13) */
  w12 += w13;
  /* #335: @13 = (@3*@43) */
  w13  = (w3*w43);
  /* #336: @45 = (@8*@31) */
  w45  = (w8*w31);
  /* #337: @13 = (@13-@45) */
  w13 -= w45;
  /* #338: @45 = (@5*@42) */
  w45  = (w5*w42);
  /* #339: @13 = (@13+@45) */
  w13 += w45;
  /* #340: @45 = (@7*@41) */
  w45  = (w7*w41);
  /* #341: @13 = (@13-@45) */
  w13 -= w45;
  /* #342: @13 = (@13+@32) */
  w13 += w32;
  /* #343: @32 = (@7*@31) */
  w32  = (w7*w31);
  /* #344: @45 = (@5*@43) */
  w45  = (w5*w43);
  /* #345: @32 = (@32+@45) */
  w32 += w45;
  /* #346: @45 = (@3*@42) */
  w45  = (w3*w42);
  /* #347: @32 = (@32-@45) */
  w32 -= w45;
  /* #348: @45 = (@8*@41) */
  w45  = (w8*w41);
  /* #349: @32 = (@32-@45) */
  w32 -= w45;
  /* #350: @32 = (@32+@11) */
  w32 += w11;
  /* #351: @31 = (@5*@31) */
  w31  = (w5*w31);
  /* #352: @43 = (@7*@43) */
  w43  = (w7*w43);
  /* #353: @31 = (@31-@43) */
  w31 -= w43;
  /* #354: @42 = (@8*@42) */
  w42  = (w8*w42);
  /* #355: @31 = (@31+@42) */
  w31 += w42;
  /* #356: @41 = (@3*@41) */
  w41  = (w3*w41);
  /* #357: @31 = (@31-@41) */
  w31 -= w41;
  /* #358: @31 = (@31+@0) */
  w31 += w0;
  /* #359: @17 = vertcat(@9, @10, @33, @15, @6, @16, @44, @12, @13, @32, @31, @2, @39, @40, @14) */
  rr=w17;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w33;
  *rr++ = w15;
  *rr++ = w6;
  *rr++ = w16;
  *rr++ = w44;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w32;
  *rr++ = w31;
  *rr++ = w2;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w14;
  /* #360: @19 = @17[:11] */
  for (rr=w19, ss=w17+0; ss!=w17+11; ss+=1) *rr++ = *ss;
  /* #361: (@34[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @19) */
  for (cii=casadi_s10, rr=w34, ss=w19; cii!=casadi_s10+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #362: @19 = @17[:11] */
  for (rr=w19, ss=w17+0; ss!=w17+11; ss+=1) *rr++ = *ss;
  /* #363: (@34[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @19) */
  for (cii=casadi_s11, rr=w34, ss=w19; cii!=casadi_s11+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #364: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #365: @36 = 00 */
  /* #366: @37 = 00 */
  /* #367: @27 = ones(15x1,3nz) */
  casadi_fill(w27, 3, 1.);
  /* #368: {NULL, NULL, @9, NULL, NULL, NULL, @10, NULL, NULL, @33, NULL, NULL, NULL, NULL, NULL} = vertsplit(@27) */
  w9 = w27[0];
  w10 = w27[1];
  w33 = w27[2];
  /* #369: @38 = 00 */
  /* #370: @15 = vertcat(@36, @37, @9, @38) */
  rr=(&w15);
  *rr++ = w9;
  /* #371: @9 = @15' */
  casadi_copy((&w15), 1, (&w9));
  /* #372: @22 = mac(@9,@25,@22) */
  casadi_mtimes((&w9), casadi_s12, w25, casadi_s1, w22, casadi_s0, w, 0);
  /* #373: @22 = @22' */
  /* #374: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #375: @15 = @15' */
  /* #376: @24 = mac(@15,@28,@24) */
  casadi_mtimes((&w15), casadi_s12, w28, casadi_s1, w24, casadi_s0, w, 0);
  /* #377: @24 = @24' */
  /* #378: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #379: {@15, @9, @6, @16} = vertsplit(@22) */
  w15 = w22[0];
  w9 = w22[1];
  w6 = w22[2];
  w16 = w22[3];
  /* #380: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #381: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #382: @44 = @10[0] */
  for (rr=(&w44), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #383: @44 = (-@44) */
  w44 = (- w44 );
  /* #384: @10 = @44' */
  casadi_copy((&w44), 1, (&w10));
  /* #385: @27 = mac(@10,@21,@27) */
  casadi_mtimes((&w10), casadi_s13, w21, casadi_s4, w27, casadi_s3, w, 0);
  /* #386: @27 = @27' */
  /* #387: @20 = zeros(1x3) */
  casadi_clear(w20, 3);
  /* #388: @44 = @44' */
  /* #389: @20 = mac(@44,@30,@20) */
  casadi_mtimes((&w44), casadi_s13, w30, casadi_s4, w20, casadi_s3, w, 0);
  /* #390: @20 = @20' */
  /* #391: @27 = (@27+@20) */
  for (i=0, rr=w27, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #392: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #393: (@19[:3] += @27) */
  for (rr=w19+0, ss=w27; rr!=w19+3; rr+=1) *rr += *ss++;
  /* #394: {@44, @10, @12, @13, @32, @31, @2, @39, @40, @14, @0} = vertsplit(@19) */
  w44 = w19[0];
  w10 = w19[1];
  w12 = w19[2];
  w13 = w19[3];
  w32 = w19[4];
  w31 = w19[5];
  w2 = w19[6];
  w39 = w19[7];
  w40 = w19[8];
  w14 = w19[9];
  w0 = w19[10];
  /* #395: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #396: @41 = (@8*@33) */
  w41  = (w8*w33);
  /* #397: @41 = (-@41) */
  w41 = (- w41 );
  /* #398: @42 = (@3*@33) */
  w42  = (w3*w33);
  /* #399: @42 = (-@42) */
  w42 = (- w42 );
  /* #400: @43 = (@5*@33) */
  w43  = (w5*w33);
  /* #401: @33 = (@7*@33) */
  w33  = (w7*w33);
  /* #402: @24 = vertcat(@41, @42, @43, @33) */
  rr=w24;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w33;
  /* #403: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #404: @27 = @27' */
  /* #405: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #406: @27 = @27' */
  /* #407: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #408: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #409: @27 = @27' */
  /* #410: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #411: @27 = @27' */
  /* #412: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #413: {@41, @42, @43, @33} = vertsplit(@22) */
  w41 = w22[0];
  w42 = w22[1];
  w43 = w22[2];
  w33 = w22[3];
  /* #414: @11 = (@3*@33) */
  w11  = (w3*w33);
  /* #415: @45 = (@8*@43) */
  w45  = (w8*w43);
  /* #416: @11 = (@11+@45) */
  w11 += w45;
  /* #417: @45 = (@7*@42) */
  w45  = (w7*w42);
  /* #418: @11 = (@11+@45) */
  w11 += w45;
  /* #419: @45 = (@5*@41) */
  w45  = (w5*w41);
  /* #420: @11 = (@11+@45) */
  w11 += w45;
  /* #421: @11 = (@11+@13) */
  w11 += w13;
  /* #422: @13 = (@3*@43) */
  w13  = (w3*w43);
  /* #423: @45 = (@8*@33) */
  w45  = (w8*w33);
  /* #424: @13 = (@13-@45) */
  w13 -= w45;
  /* #425: @45 = (@5*@42) */
  w45  = (w5*w42);
  /* #426: @13 = (@13+@45) */
  w13 += w45;
  /* #427: @45 = (@7*@41) */
  w45  = (w7*w41);
  /* #428: @13 = (@13-@45) */
  w13 -= w45;
  /* #429: @13 = (@13+@32) */
  w13 += w32;
  /* #430: @32 = (@7*@33) */
  w32  = (w7*w33);
  /* #431: @45 = (@5*@43) */
  w45  = (w5*w43);
  /* #432: @32 = (@32+@45) */
  w32 += w45;
  /* #433: @45 = (@3*@42) */
  w45  = (w3*w42);
  /* #434: @32 = (@32-@45) */
  w32 -= w45;
  /* #435: @45 = (@8*@41) */
  w45  = (w8*w41);
  /* #436: @32 = (@32-@45) */
  w32 -= w45;
  /* #437: @32 = (@32+@31) */
  w32 += w31;
  /* #438: @33 = (@5*@33) */
  w33  = (w5*w33);
  /* #439: @43 = (@7*@43) */
  w43  = (w7*w43);
  /* #440: @33 = (@33-@43) */
  w33 -= w43;
  /* #441: @42 = (@8*@42) */
  w42  = (w8*w42);
  /* #442: @33 = (@33+@42) */
  w33 += w42;
  /* #443: @41 = (@3*@41) */
  w41  = (w3*w41);
  /* #444: @33 = (@33-@41) */
  w33 -= w41;
  /* #445: @33 = (@33+@2) */
  w33 += w2;
  /* #446: @17 = vertcat(@15, @9, @6, @16, @44, @10, @12, @11, @13, @32, @33, @39, @40, @14, @0) */
  rr=w17;
  *rr++ = w15;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w16;
  *rr++ = w44;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w14;
  *rr++ = w0;
  /* #447: @19 = @17[:11] */
  for (rr=w19, ss=w17+0; ss!=w17+11; ss+=1) *rr++ = *ss;
  /* #448: (@34[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @19) */
  for (cii=casadi_s14, rr=w34, ss=w19; cii!=casadi_s14+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #449: @19 = @17[:11] */
  for (rr=w19, ss=w17+0; ss!=w17+11; ss+=1) *rr++ = *ss;
  /* #450: (@34[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @19) */
  for (cii=casadi_s15, rr=w34, ss=w19; cii!=casadi_s15+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #451: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #452: @36 = 00 */
  /* #453: @37 = 00 */
  /* #454: @38 = 00 */
  /* #455: @46 = ones(15x1,2nz) */
  casadi_fill(w46, 2, 1.);
  /* #456: {NULL, NULL, NULL, @15, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL} = vertsplit(@46) */
  w15 = w46[0];
  w9 = w46[1];
  /* #457: @6 = vertcat(@36, @37, @38, @15) */
  rr=(&w6);
  *rr++ = w15;
  /* #458: @15 = @6' */
  casadi_copy((&w6), 1, (&w15));
  /* #459: @22 = mac(@15,@25,@22) */
  casadi_mtimes((&w15), casadi_s16, w25, casadi_s1, w22, casadi_s0, w, 0);
  /* #460: @22 = @22' */
  /* #461: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #462: @6 = @6' */
  /* #463: @24 = mac(@6,@28,@24) */
  casadi_mtimes((&w6), casadi_s16, w28, casadi_s1, w24, casadi_s0, w, 0);
  /* #464: @24 = @24' */
  /* #465: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #466: {@6, @15, @16, @44} = vertsplit(@22) */
  w6 = w22[0];
  w15 = w22[1];
  w16 = w22[2];
  w44 = w22[3];
  /* #467: @36 = 00 */
  /* #468: @37 = 00 */
  /* #469: @38 = 00 */
  /* #470: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #471: @10 = (@3*@9) */
  w10  = (w3*w9);
  /* #472: @10 = (-@10) */
  w10 = (- w10 );
  /* #473: @12 = (@8*@9) */
  w12  = (w8*w9);
  /* #474: @11 = (@7*@9) */
  w11  = (w7*w9);
  /* #475: @11 = (-@11) */
  w11 = (- w11 );
  /* #476: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #477: @24 = vertcat(@10, @12, @11, @9) */
  rr=w24;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w9;
  /* #478: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #479: @27 = @27' */
  /* #480: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #481: @27 = @27' */
  /* #482: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #483: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #484: @27 = @27' */
  /* #485: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #486: @27 = @27' */
  /* #487: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #488: {@4, @10, @12, @11} = vertsplit(@22) */
  w4 = w22[0];
  w10 = w22[1];
  w12 = w22[2];
  w11 = w22[3];
  /* #489: @9 = (@3*@11) */
  w9  = (w3*w11);
  /* #490: @13 = (@8*@12) */
  w13  = (w8*w12);
  /* #491: @9 = (@9+@13) */
  w9 += w13;
  /* #492: @13 = (@7*@10) */
  w13  = (w7*w10);
  /* #493: @9 = (@9+@13) */
  w9 += w13;
  /* #494: @13 = (@5*@4) */
  w13  = (w5*w4);
  /* #495: @9 = (@9+@13) */
  w9 += w13;
  /* #496: @13 = (@3*@12) */
  w13  = (w3*w12);
  /* #497: @32 = (@8*@11) */
  w32  = (w8*w11);
  /* #498: @13 = (@13-@32) */
  w13 -= w32;
  /* #499: @32 = (@5*@10) */
  w32  = (w5*w10);
  /* #500: @13 = (@13+@32) */
  w13 += w32;
  /* #501: @32 = (@7*@4) */
  w32  = (w7*w4);
  /* #502: @13 = (@13-@32) */
  w13 -= w32;
  /* #503: @32 = (@7*@11) */
  w32  = (w7*w11);
  /* #504: @33 = (@5*@12) */
  w33  = (w5*w12);
  /* #505: @32 = (@32+@33) */
  w32 += w33;
  /* #506: @33 = (@3*@10) */
  w33  = (w3*w10);
  /* #507: @32 = (@32-@33) */
  w32 -= w33;
  /* #508: @33 = (@8*@4) */
  w33  = (w8*w4);
  /* #509: @32 = (@32-@33) */
  w32 -= w33;
  /* #510: @5 = (@5*@11) */
  w5 *= w11;
  /* #511: @7 = (@7*@12) */
  w7 *= w12;
  /* #512: @5 = (@5-@7) */
  w5 -= w7;
  /* #513: @8 = (@8*@10) */
  w8 *= w10;
  /* #514: @5 = (@5+@8) */
  w5 += w8;
  /* #515: @3 = (@3*@4) */
  w3 *= w4;
  /* #516: @5 = (@5-@3) */
  w5 -= w3;
  /* #517: @47 = 00 */
  /* #518: @48 = 00 */
  /* #519: @49 = 00 */
  /* #520: @50 = 00 */
  /* #521: @51 = vertcat(@6, @15, @16, @44, @36, @37, @38, @9, @13, @32, @5, @47, @48, @49, @50) */
  rr=w51;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w44;
  *rr++ = w9;
  *rr++ = w13;
  *rr++ = w32;
  *rr++ = w5;
  /* #522: @52 = @51[:8] */
  for (rr=w52, ss=w51+0; ss!=w51+8; ss+=1) *rr++ = *ss;
  /* #523: (@34[:50:25;12:16] = @52) */
  for (rr=w34+0, ss=w52; rr!=w34+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *ss++;
  /* #524: @52 = @51[:8] */
  for (rr=w52, ss=w51+0; ss!=w51+8; ss+=1) *rr++ = *ss;
  /* #525: (@34[:50:25;3:19:4] = @52) */
  for (rr=w34+0, ss=w52; rr!=w34+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *ss++;
  /* #526: @53 = @34' */
  casadi_trans(w34,casadi_s17, w53, casadi_s17, iw);
  /* #527: output[2][0] = @53 */
  casadi_copy(w53, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s20;
    case 3: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s21;
    case 2: return casadi_s17;
    case 3: return casadi_s20;
    case 4: return casadi_s23;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 20;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 241;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
