/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* Drone_ode_cost_ext_cost_0_fun_jac:(i0[8],i1[4],i2[],i3[12])->(o0,o1[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+18, *w15=w+30, *w16=w+34, *w17=w+42, *w18=w+46, *w19=w+62, *w20=w+66, *w21=w+70, *w22=w+86;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @15 = @14[:4] */
  for (rr=w15, ss=w14+0; ss!=w14+4; ss+=1) *rr++ = *ss;
  /* #16: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #17: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #18: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #19: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #20: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #21: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #22: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #23: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #24: @16 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #25: @17 = @16[:4] */
  for (rr=w17, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #26: @15 = (@15-@17) */
  for (i=0, rr=w15, cs=w17; i<4; ++i) (*rr++) -= (*cs++);
  /* #27: @17 = @15' */
  casadi_copy(w15, 4, w17);
  /* #28: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #29: @2 = 3 */
  w2 = 3.;
  /* #30: (@18[0] = @2) */
  for (rr=w18+0, ss=(&w2); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #31: @2 = 3 */
  w2 = 3.;
  /* #32: (@18[5] = @2) */
  for (rr=w18+5, ss=(&w2); rr!=w18+6; rr+=1) *rr = *ss++;
  /* #33: @2 = 3 */
  w2 = 3.;
  /* #34: (@18[10] = @2) */
  for (rr=w18+10, ss=(&w2); rr!=w18+11; rr+=1) *rr = *ss++;
  /* #35: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #36: (@18[15] = @2) */
  for (rr=w18+15, ss=(&w2); rr!=w18+16; rr+=1) *rr = *ss++;
  /* #37: @1 = mac(@17,@18,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #38: @0 = mac(@1,@15,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #39: @2 = 0 */
  w2 = 0.;
  /* #40: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #41: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #42: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #43: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #44: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #45: @19 = vertcat(@3, @4, @5, @6) */
  rr=w19;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #46: @20 = @19' */
  casadi_copy(w19, 4, w20);
  /* #47: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #48: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #49: (@21[0] = @3) */
  for (rr=w21+0, ss=(&w3); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #50: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #51: (@21[5] = @3) */
  for (rr=w21+5, ss=(&w3); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #52: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #53: (@21[10] = @3) */
  for (rr=w21+10, ss=(&w3); rr!=w21+11; rr+=1) *rr = *ss++;
  /* #54: @3 = 1.5 */
  w3 = 1.5000000000000000e+00;
  /* #55: (@21[15] = @3) */
  for (rr=w21+15, ss=(&w3); rr!=w21+16; rr+=1) *rr = *ss++;
  /* #56: @17 = mac(@20,@21,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #57: @2 = mac(@17,@19,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w19+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #58: @0 = (@0+@2) */
  w0 += w2;
  /* #59: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #60: @17 = @17' */
  /* #61: @20 = zeros(1x4) */
  casadi_clear(w20, 4);
  /* #62: @19 = @19' */
  /* #63: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #64: @20 = mac(@19,@22,@20) */
  for (i=0, rr=w20; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w19+j, tt=w22+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #65: @20 = @20' */
  /* #66: @17 = (@17+@20) */
  for (i=0, rr=w17, cs=w20; i<4; ++i) (*rr++) += (*cs++);
  /* #67: {@0, @2, @3, @4} = vertsplit(@17) */
  w0 = w17[0];
  w2 = w17[1];
  w3 = w17[2];
  w4 = w17[3];
  /* #68: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #69: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #70: output[1][2] = @3 */
  if (res[1]) res[1][2] = w3;
  /* #71: output[1][3] = @4 */
  if (res[1]) res[1][3] = w4;
  /* #72: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #73: @1 = @1' */
  /* #74: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #75: @15 = @15' */
  /* #76: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #77: @17 = mac(@15,@22,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w15+j, tt=w22+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #78: @17 = @17' */
  /* #79: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #80: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #81: (@16[:4] += @1) */
  for (rr=w16+0, ss=w1; rr!=w16+4; rr+=1) *rr += *ss++;
  /* #82: {@4, @3, @2, @0, @5, @6, @7, @8} = vertsplit(@16) */
  w4 = w16[0];
  w3 = w16[1];
  w2 = w16[2];
  w0 = w16[3];
  w5 = w16[4];
  w6 = w16[5];
  w7 = w16[6];
  w8 = w16[7];
  /* #83: output[1][4] = @4 */
  if (res[1]) res[1][4] = w4;
  /* #84: output[1][5] = @3 */
  if (res[1]) res[1][5] = w3;
  /* #85: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #86: output[1][7] = @0 */
  if (res[1]) res[1][7] = w0;
  /* #87: output[1][8] = @5 */
  if (res[1]) res[1][8] = w5;
  /* #88: output[1][9] = @6 */
  if (res[1]) res[1][9] = w6;
  /* #89: output[1][10] = @7 */
  if (res[1]) res[1][10] = w7;
  /* #90: output[1][11] = @8 */
  if (res[1]) res[1][11] = w8;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_0_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 102;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
