/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s5[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s6[27] = {8, 8, 0, 4, 8, 12, 16, 16, 16, 16, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s7[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s10[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s11[11] = {0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_e_fun_jac_hess:(i0[8],i1[],i2[],i3[12])->(o0,o1[8],o2[8x8,16nz],o3[],o4[0x8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+18, *w15=w+30, *w16=w+34, *w17=w+42, *w18=w+46, *w19=w+62, *w20=w+78, *w21=w+94;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @15 = @14[:4] */
  for (rr=w15, ss=w14+0; ss!=w14+4; ss+=1) *rr++ = *ss;
  /* #16: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #17: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #18: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #19: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #20: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #21: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #22: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #23: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #24: @16 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #25: @17 = @16[:4] */
  for (rr=w17, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #26: @15 = (@15-@17) */
  for (i=0, rr=w15, cs=w17; i<4; ++i) (*rr++) -= (*cs++);
  /* #27: @17 = @15' */
  casadi_copy(w15, 4, w17);
  /* #28: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #29: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #30: (@18[0] = @2) */
  for (rr=w18+0, ss=(&w2); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #31: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #32: (@18[5] = @2) */
  for (rr=w18+5, ss=(&w2); rr!=w18+6; rr+=1) *rr = *ss++;
  /* #33: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #34: (@18[10] = @2) */
  for (rr=w18+10, ss=(&w2); rr!=w18+11; rr+=1) *rr = *ss++;
  /* #35: @2 = 1 */
  w2 = 1.;
  /* #36: (@18[15] = @2) */
  for (rr=w18+15, ss=(&w2); rr!=w18+16; rr+=1) *rr = *ss++;
  /* #37: @1 = mac(@17,@18,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #38: @0 = mac(@1,@15,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #39: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #40: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #41: @1 = @1' */
  /* #42: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #43: @15 = @15' */
  /* #44: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #45: @17 = mac(@15,@19,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w15+j, tt=w19+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #46: @17 = @17' */
  /* #47: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #48: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #49: (@16[:4] += @1) */
  for (rr=w16+0, ss=w1; rr!=w16+4; rr+=1) *rr += *ss++;
  /* #50: output[1][0] = @16 */
  casadi_copy(w16, 8, res[1]);
  /* #51: @20 = zeros(8x8,16nz) */
  casadi_clear(w20, 16);
  /* #52: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #53: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #54: @21 = ones(8x1,5nz) */
  casadi_fill(w21, 5, 1.);
  /* #55: {@0, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@21) */
  w0 = w21[0];
  /* #56: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #57: @2 = (-@2) */
  w2 = (- w2 );
  /* #58: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #59: @1 = mac(@0,@18,@1) */
  casadi_mtimes((&w0), casadi_s2, w18, casadi_s1, w1, casadi_s0, w, 0);
  /* #60: @1 = @1' */
  /* #61: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #62: @2 = @2' */
  /* #63: @17 = mac(@2,@19,@17) */
  casadi_mtimes((&w2), casadi_s2, w19, casadi_s1, w17, casadi_s0, w, 0);
  /* #64: @17 = @17' */
  /* #65: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #66: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #67: (@16[:4] += @1) */
  for (rr=w16+0, ss=w1; rr!=w16+4; rr+=1) *rr += *ss++;
  /* #68: @1 = @16[:4] */
  for (rr=w1, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #69: (@20[:4] = @1) */
  for (rr=w20+0, ss=w1; rr!=w20+4; rr+=1) *rr = *ss++;
  /* #70: @1 = @16[:4] */
  for (rr=w1, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #71: (@20[:16:4] = @1) */
  for (rr=w20+0, ss=w1; rr!=w20+16; rr+=4) *rr = *ss++;
  /* #72: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #73: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #74: @2 = ones(8x1,1nz) */
  w2 = 1.;
  /* #75: {NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #76: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #77: @2 = (-@2) */
  w2 = (- w2 );
  /* #78: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #79: @1 = mac(@0,@18,@1) */
  casadi_mtimes((&w0), casadi_s3, w18, casadi_s1, w1, casadi_s0, w, 0);
  /* #80: @1 = @1' */
  /* #81: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #82: @2 = @2' */
  /* #83: @17 = mac(@2,@19,@17) */
  casadi_mtimes((&w2), casadi_s3, w19, casadi_s1, w17, casadi_s0, w, 0);
  /* #84: @17 = @17' */
  /* #85: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #86: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #87: (@16[:4] += @1) */
  for (rr=w16+0, ss=w1; rr!=w16+4; rr+=1) *rr += *ss++;
  /* #88: @1 = @16[:4] */
  for (rr=w1, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #89: (@20[4:8] = @1) */
  for (rr=w20+4, ss=w1; rr!=w20+8; rr+=1) *rr = *ss++;
  /* #90: @1 = @16[:4] */
  for (rr=w1, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #91: (@20[1:17:4] = @1) */
  for (rr=w20+1, ss=w1; rr!=w20+17; rr+=4) *rr = *ss++;
  /* #92: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #93: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #94: @2 = ones(8x1,1nz) */
  w2 = 1.;
  /* #95: {NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #96: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #97: @2 = (-@2) */
  w2 = (- w2 );
  /* #98: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #99: @1 = mac(@0,@18,@1) */
  casadi_mtimes((&w0), casadi_s4, w18, casadi_s1, w1, casadi_s0, w, 0);
  /* #100: @1 = @1' */
  /* #101: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #102: @2 = @2' */
  /* #103: @17 = mac(@2,@19,@17) */
  casadi_mtimes((&w2), casadi_s4, w19, casadi_s1, w17, casadi_s0, w, 0);
  /* #104: @17 = @17' */
  /* #105: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #106: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #107: (@16[:4] += @1) */
  for (rr=w16+0, ss=w1; rr!=w16+4; rr+=1) *rr += *ss++;
  /* #108: @1 = @16[:4] */
  for (rr=w1, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #109: (@20[8:12] = @1) */
  for (rr=w20+8, ss=w1; rr!=w20+12; rr+=1) *rr = *ss++;
  /* #110: @1 = @16[:4] */
  for (rr=w1, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #111: (@20[2:18:4] = @1) */
  for (rr=w20+2, ss=w1; rr!=w20+18; rr+=4) *rr = *ss++;
  /* #112: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #113: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #114: @2 = ones(8x1,1nz) */
  w2 = 1.;
  /* #115: {NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #116: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #117: @2 = (-@2) */
  w2 = (- w2 );
  /* #118: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #119: @1 = mac(@0,@18,@1) */
  casadi_mtimes((&w0), casadi_s5, w18, casadi_s1, w1, casadi_s0, w, 0);
  /* #120: @1 = @1' */
  /* #121: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #122: @2 = @2' */
  /* #123: @17 = mac(@2,@19,@17) */
  casadi_mtimes((&w2), casadi_s5, w19, casadi_s1, w17, casadi_s0, w, 0);
  /* #124: @17 = @17' */
  /* #125: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #126: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #127: (@16[:4] += @1) */
  for (rr=w16+0, ss=w1; rr!=w16+4; rr+=1) *rr += *ss++;
  /* #128: @1 = @16[:4] */
  for (rr=w1, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #129: (@20[12:16] = @1) */
  for (rr=w20+12, ss=w1; rr!=w20+16; rr+=1) *rr = *ss++;
  /* #130: @1 = @16[:4] */
  for (rr=w1, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #131: (@20[3:19:4] = @1) */
  for (rr=w20+3, ss=w1; rr!=w20+19; rr+=4) *rr = *ss++;
  /* #132: @19 = @20' */
  casadi_trans(w20,casadi_s6, w19, casadi_s6, iw);
  /* #133: output[2][0] = @19 */
  casadi_copy(w19, 16, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s8;
    case 3: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s7;
    case 2: return casadi_s6;
    case 3: return casadi_s8;
    case 4: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 99;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
