/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* Drone_ode_cost_ext_cost_fun_jac:(i0[11],i1[4],i2[],i3[15])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w19=w+38, *w20=w+49, *w21=w+52, *w22=w+61, *w23=w+65, *w24=w+69, *w25=w+73, *w26=w+89, *w27=w+93, *w28=w+96, *w29=w+112, *w30=w+115, w31, w32;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, ss=w17+0; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #19: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #20: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #21: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #22: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #23: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #24: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #25: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #26: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #27: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #28: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #29: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #30: @19 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #31: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #32: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #34: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #35: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #36: (@21[0] = @2) */
  for (rr=w21+0, ss=(&w2); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #37: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #38: (@21[4] = @2) */
  for (rr=w21+4, ss=(&w2); rr!=w21+5; rr+=1) *rr = *ss++;
  /* #39: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #40: (@21[8] = @2) */
  for (rr=w21+8, ss=(&w2); rr!=w21+9; rr+=1) *rr = *ss++;
  /* #41: @1 = mac(@20,@21,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #42: @0 = mac(@1,@18,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #43: @2 = 0 */
  w2 = 0.;
  /* #44: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #45: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #46: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #47: @13 = input[1][2] */
  w13 = arg[1] ? arg[1][2] : 0;
  /* #48: @14 = input[1][3] */
  w14 = arg[1] ? arg[1][3] : 0;
  /* #49: @23 = vertcat(@3, @4, @13, @14) */
  rr=w23;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w13;
  *rr++ = w14;
  /* #50: @24 = @23' */
  casadi_copy(w23, 4, w24);
  /* #51: @25 = zeros(4x4) */
  casadi_clear(w25, 16);
  /* #52: @3 = 1 */
  w3 = 1.;
  /* #53: (@25[0] = @3) */
  for (rr=w25+0, ss=(&w3); rr!=w25+1; rr+=1) *rr = *ss++;
  /* #54: @3 = 1 */
  w3 = 1.;
  /* #55: (@25[5] = @3) */
  for (rr=w25+5, ss=(&w3); rr!=w25+6; rr+=1) *rr = *ss++;
  /* #56: @3 = 1 */
  w3 = 1.;
  /* #57: (@25[10] = @3) */
  for (rr=w25+10, ss=(&w3); rr!=w25+11; rr+=1) *rr = *ss++;
  /* #58: @3 = 1 */
  w3 = 1.;
  /* #59: (@25[15] = @3) */
  for (rr=w25+15, ss=(&w3); rr!=w25+16; rr+=1) *rr = *ss++;
  /* #60: @22 = mac(@24,@25,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #61: @2 = mac(@22,@23,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #62: @0 = (@0+@2) */
  w0 += w2;
  /* #63: @2 = 1 */
  w2 = 1.;
  /* #64: @6 = (-@6) */
  w6 = (- w6 );
  /* #65: @7 = (-@7) */
  w7 = (- w7 );
  /* #66: @8 = (-@8) */
  w8 = (- w8 );
  /* #67: @24 = vertcat(@5, @6, @7, @8) */
  rr=w24;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #68: @26 = @17[3:7] */
  for (rr=w26, ss=w17+3; ss!=w17+7; ss+=1) *rr++ = *ss;
  /* #69: @5 = ||@26||_F */
  w5 = sqrt(casadi_dot(4, w26, w26));
  /* #70: @24 = (@24/@5) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w5;
  /* #71: @5 = @24[0] */
  for (rr=(&w5), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #72: @6 = (@5*@9) */
  w6  = (w5*w9);
  /* #73: @7 = @24[1] */
  for (rr=(&w7), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #74: @8 = (@7*@10) */
  w8  = (w7*w10);
  /* #75: @6 = (@6-@8) */
  w6 -= w8;
  /* #76: @8 = @24[2] */
  for (rr=(&w8), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #77: @3 = (@8*@11) */
  w3  = (w8*w11);
  /* #78: @6 = (@6-@3) */
  w6 -= w3;
  /* #79: @3 = @24[3] */
  for (rr=(&w3), ss=w24+3; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #80: @4 = (@3*@12) */
  w4  = (w3*w12);
  /* #81: @6 = (@6-@4) */
  w6 -= w4;
  /* #82: @2 = (@2-@6) */
  w2 -= w6;
  /* #83: @0 = (@0+@2) */
  w0 += w2;
  /* #84: @2 = 0 */
  w2 = 0.;
  /* #85: @4 = 7 */
  w4 = 7.;
  /* #86: @13 = (@5*@10) */
  w13  = (w5*w10);
  /* #87: @14 = (@7*@9) */
  w14  = (w7*w9);
  /* #88: @13 = (@13+@14) */
  w13 += w14;
  /* #89: @14 = (@8*@12) */
  w14  = (w8*w12);
  /* #90: @13 = (@13+@14) */
  w13 += w14;
  /* #91: @14 = (@3*@11) */
  w14  = (w3*w11);
  /* #92: @13 = (@13-@14) */
  w13 -= w14;
  /* #93: @14 = (@5*@11) */
  w14  = (w5*w11);
  /* #94: @15 = (@7*@12) */
  w15  = (w7*w12);
  /* #95: @14 = (@14-@15) */
  w14 -= w15;
  /* #96: @15 = (@8*@9) */
  w15  = (w8*w9);
  /* #97: @14 = (@14+@15) */
  w14 += w15;
  /* #98: @15 = (@3*@10) */
  w15  = (w3*w10);
  /* #99: @14 = (@14+@15) */
  w14 += w15;
  /* #100: @12 = (@5*@12) */
  w12  = (w5*w12);
  /* #101: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #102: @12 = (@12+@11) */
  w12 += w11;
  /* #103: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #104: @12 = (@12-@10) */
  w12 -= w10;
  /* #105: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #106: @12 = (@12+@9) */
  w12 += w9;
  /* #107: @24 = vertcat(@6, @13, @14, @12) */
  rr=w24;
  *rr++ = w6;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w12;
  /* #108: @20 = @24[1:4] */
  for (rr=w20, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #109: @20 = @20' */
  /* #110: @20 = (@4*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #111: @27 = @24[1:4] */
  for (rr=w27, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #112: @2 = mac(@20,@27,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #113: @0 = (@0+@2) */
  w0 += w2;
  /* #114: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #115: @22 = @22' */
  /* #116: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #117: @23 = @23' */
  /* #118: @28 = @25' */
  for (i=0, rr=w28, cs=w25; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #119: @24 = mac(@23,@28,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w28+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #120: @24 = @24' */
  /* #121: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #122: {@0, @2, @6, @13} = vertsplit(@22) */
  w0 = w22[0];
  w2 = w22[1];
  w6 = w22[2];
  w13 = w22[3];
  /* #123: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #124: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #125: output[1][2] = @6 */
  if (res[1]) res[1][2] = w6;
  /* #126: output[1][3] = @13 */
  if (res[1]) res[1][3] = w13;
  /* #127: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #128: @1 = @1' */
  /* #129: @29 = zeros(1x3) */
  casadi_clear(w29, 3);
  /* #130: @18 = @18' */
  /* #131: @30 = @21' */
  for (i=0, rr=w30, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #132: @29 = mac(@18,@30,@29) */
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #133: @29 = @29' */
  /* #134: @1 = (@1+@29) */
  for (i=0, rr=w1, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #135: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #136: (@19[:3] += @1) */
  for (rr=w19+0, ss=w1; rr!=w19+3; rr+=1) *rr += *ss++;
  /* #137: {@13, @6, @2, @0, @14, @12, @9, @10, @11, @15, @16} = vertsplit(@19) */
  w13 = w19[0];
  w6 = w19[1];
  w2 = w19[2];
  w0 = w19[3];
  w14 = w19[4];
  w12 = w19[5];
  w9 = w19[6];
  w10 = w19[7];
  w11 = w19[8];
  w15 = w19[9];
  w16 = w19[10];
  /* #138: output[1][4] = @13 */
  if (res[1]) res[1][4] = w13;
  /* #139: output[1][5] = @6 */
  if (res[1]) res[1][5] = w6;
  /* #140: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #141: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #142: @20 = @20' */
  /* #143: (@22[1:4] += @20) */
  for (rr=w22+1, ss=w20; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #144: @27 = @27' */
  /* #145: @27 = (@4*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #146: @27 = @27' */
  /* #147: (@22[1:4] += @27) */
  for (rr=w22+1, ss=w27; rr!=w22+4; rr+=1) *rr += *ss++;
  /* #148: {@4, @2, @6, @13} = vertsplit(@22) */
  w4 = w22[0];
  w2 = w22[1];
  w6 = w22[2];
  w13 = w22[3];
  /* #149: @31 = (@3*@13) */
  w31  = (w3*w13);
  /* #150: @32 = (@8*@6) */
  w32  = (w8*w6);
  /* #151: @31 = (@31+@32) */
  w31 += w32;
  /* #152: @32 = (@7*@2) */
  w32  = (w7*w2);
  /* #153: @31 = (@31+@32) */
  w31 += w32;
  /* #154: @32 = -1 */
  w32 = -1.;
  /* #155: @32 = (@32+@4) */
  w32 += w4;
  /* #156: @4 = (@5*@32) */
  w4  = (w5*w32);
  /* #157: @31 = (@31+@4) */
  w31 += w4;
  /* #158: @31 = (@31+@0) */
  w31 += w0;
  /* #159: output[1][7] = @31 */
  if (res[1]) res[1][7] = w31;
  /* #160: @31 = (@3*@6) */
  w31  = (w3*w6);
  /* #161: @0 = (@8*@13) */
  w0  = (w8*w13);
  /* #162: @31 = (@31-@0) */
  w31 -= w0;
  /* #163: @0 = (@5*@2) */
  w0  = (w5*w2);
  /* #164: @31 = (@31+@0) */
  w31 += w0;
  /* #165: @0 = (@7*@32) */
  w0  = (w7*w32);
  /* #166: @31 = (@31-@0) */
  w31 -= w0;
  /* #167: @31 = (@31+@14) */
  w31 += w14;
  /* #168: output[1][8] = @31 */
  if (res[1]) res[1][8] = w31;
  /* #169: @31 = (@7*@13) */
  w31  = (w7*w13);
  /* #170: @14 = (@5*@6) */
  w14  = (w5*w6);
  /* #171: @31 = (@31+@14) */
  w31 += w14;
  /* #172: @14 = (@3*@2) */
  w14  = (w3*w2);
  /* #173: @31 = (@31-@14) */
  w31 -= w14;
  /* #174: @14 = (@8*@32) */
  w14  = (w8*w32);
  /* #175: @31 = (@31-@14) */
  w31 -= w14;
  /* #176: @31 = (@31+@12) */
  w31 += w12;
  /* #177: output[1][9] = @31 */
  if (res[1]) res[1][9] = w31;
  /* #178: @5 = (@5*@13) */
  w5 *= w13;
  /* #179: @7 = (@7*@6) */
  w7 *= w6;
  /* #180: @5 = (@5-@7) */
  w5 -= w7;
  /* #181: @8 = (@8*@2) */
  w8 *= w2;
  /* #182: @5 = (@5+@8) */
  w5 += w8;
  /* #183: @3 = (@3*@32) */
  w3 *= w32;
  /* #184: @5 = (@5-@3) */
  w5 -= w3;
  /* #185: @5 = (@5+@9) */
  w5 += w9;
  /* #186: output[1][10] = @5 */
  if (res[1]) res[1][10] = w5;
  /* #187: output[1][11] = @10 */
  if (res[1]) res[1][11] = w10;
  /* #188: output[1][12] = @11 */
  if (res[1]) res[1][12] = w11;
  /* #189: output[1][13] = @15 */
  if (res[1]) res[1][13] = w15;
  /* #190: output[1][14] = @16 */
  if (res[1]) res[1][14] = w16;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 126;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
