/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s6[15] = {1, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s7[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s8[39] = {8, 4, 0, 8, 16, 24, 32, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s9[8] = {8, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s10[43] = {4, 8, 0, 4, 8, 12, 16, 20, 24, 28, 32, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[3] = {0, 0, 0};
static const casadi_int casadi_s13[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s14[3] = {1, 0, 0};

static const casadi_real casadi_c0[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_constr_h_fun_jac_uxt_zt:(i0[8],i1[4],i2[],i3[12])->(o0,o1[12],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+9, *w2=w+13, *w3=w+21, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+38, *w18=w+50, *w19=w+54, *w20=w+62, *w21=w+66, *w22=w+82, *w23=w+86, *w24=w+90, *w25=w+106, *w26=w+122, *w27=w+154, *w28=w+186, *w29=w+202, *w30=w+218, *w31=w+234, *w32=w+266, *w33=w+330, *w34=w+394, *w35=w+402, *w36=w+410, *w37=w+418;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(8x1,4nz) */
  casadi_clear(w1, 4);
  /* #2: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #3: @3 = zeros(1x4) */
  casadi_clear(w3, 4);
  /* #4: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:4] */
  for (rr=w18, ss=w17+0; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #19: @5 = input[0][0] */
  w5 = arg[0] ? arg[0][0] : 0;
  /* #20: @6 = input[0][1] */
  w6 = arg[0] ? arg[0][1] : 0;
  /* #21: @7 = input[0][2] */
  w7 = arg[0] ? arg[0][2] : 0;
  /* #22: @8 = input[0][3] */
  w8 = arg[0] ? arg[0][3] : 0;
  /* #23: @9 = input[0][4] */
  w9 = arg[0] ? arg[0][4] : 0;
  /* #24: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #25: @11 = input[0][6] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #26: @12 = input[0][7] */
  w12 = arg[0] ? arg[0][7] : 0;
  /* #27: @19 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w19;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #28: @20 = @19[:4] */
  for (rr=w20, ss=w19+0; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #29: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<4; ++i) (*rr++) -= (*cs++);
  /* #30: @20 = @18' */
  casadi_copy(w18, 4, w20);
  /* #31: @20 = (@4*@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #32: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #33: @5 = 2 */
  w5 = 2.;
  /* #34: (@21[0] = @5) */
  for (rr=w21+0, ss=(&w5); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #35: @5 = 2 */
  w5 = 2.;
  /* #36: (@21[5] = @5) */
  for (rr=w21+5, ss=(&w5); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #37: @5 = 2 */
  w5 = 2.;
  /* #38: (@21[10] = @5) */
  for (rr=w21+10, ss=(&w5); rr!=w21+11; rr+=1) *rr = *ss++;
  /* #39: @5 = 2 */
  w5 = 2.;
  /* #40: (@21[15] = @5) */
  for (rr=w21+15, ss=(&w5); rr!=w21+16; rr+=1) *rr = *ss++;
  /* #41: @3 = mac(@20,@21,@3) */
  for (i=0, rr=w3; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #42: @20 = @3' */
  casadi_copy(w3, 4, w20);
  /* #43: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #44: @23 = @18' */
  casadi_copy(w18, 4, w23);
  /* #45: @24 = @21' */
  for (i=0, rr=w24, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #46: @22 = mac(@23,@24,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #47: @22 = (@4*@22) */
  for (i=0, rr=w22, cs=w22; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #48: @22 = @22' */
  /* #49: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<4; ++i) (*rr++) += (*cs++);
  /* #50: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #51: (@2[:4] += @20) */
  for (rr=w2+0, ss=w20; rr!=w2+4; rr+=1) *rr += *ss++;
  /* #52: @5 = @2[0] */
  for (rr=(&w5), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #53: (@1[0] = @5) */
  for (rr=w1+0, ss=(&w5); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #54: @5 = @2[1] */
  for (rr=(&w5), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #55: (@1[1] = @5) */
  for (rr=w1+1, ss=(&w5); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #56: @5 = @2[2] */
  for (rr=(&w5), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #57: (@1[2] = @5) */
  for (rr=w1+2, ss=(&w5); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #58: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #59: (@1[3] = @5) */
  for (rr=w1+3, ss=(&w5); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #60: @20 = @1' */
  casadi_copy(w1, 4, w20);
  /* #61: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #62: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #63: @25 = zeros(4x4) */
  casadi_clear(w25, 16);
  /* #64: @5 = cos(@8) */
  w5 = cos( w8 );
  /* #65: (@25[0] = @5) */
  for (rr=w25+0, ss=(&w5); rr!=w25+1; rr+=1) *rr = *ss++;
  /* #66: @5 = sin(@8) */
  w5 = sin( w8 );
  /* #67: @5 = (-@5) */
  w5 = (- w5 );
  /* #68: (@25[4] = @5) */
  for (rr=w25+4, ss=(&w5); rr!=w25+5; rr+=1) *rr = *ss++;
  /* #69: @5 = 0 */
  w5 = 0.;
  /* #70: (@25[8] = @5) */
  for (rr=w25+8, ss=(&w5); rr!=w25+9; rr+=1) *rr = *ss++;
  /* #71: @5 = 0 */
  w5 = 0.;
  /* #72: (@25[12] = @5) */
  for (rr=w25+12, ss=(&w5); rr!=w25+13; rr+=1) *rr = *ss++;
  /* #73: @5 = sin(@8) */
  w5 = sin( w8 );
  /* #74: (@25[1] = @5) */
  for (rr=w25+1, ss=(&w5); rr!=w25+2; rr+=1) *rr = *ss++;
  /* #75: @5 = cos(@8) */
  w5 = cos( w8 );
  /* #76: (@25[5] = @5) */
  for (rr=w25+5, ss=(&w5); rr!=w25+6; rr+=1) *rr = *ss++;
  /* #77: @5 = 0 */
  w5 = 0.;
  /* #78: (@25[9] = @5) */
  for (rr=w25+9, ss=(&w5); rr!=w25+10; rr+=1) *rr = *ss++;
  /* #79: @5 = 0 */
  w5 = 0.;
  /* #80: (@25[13] = @5) */
  for (rr=w25+13, ss=(&w5); rr!=w25+14; rr+=1) *rr = *ss++;
  /* #81: @5 = 0 */
  w5 = 0.;
  /* #82: (@25[2] = @5) */
  for (rr=w25+2, ss=(&w5); rr!=w25+3; rr+=1) *rr = *ss++;
  /* #83: @5 = 0 */
  w5 = 0.;
  /* #84: (@25[6] = @5) */
  for (rr=w25+6, ss=(&w5); rr!=w25+7; rr+=1) *rr = *ss++;
  /* #85: @5 = 1 */
  w5 = 1.;
  /* #86: (@25[10] = @5) */
  for (rr=w25+10, ss=(&w5); rr!=w25+11; rr+=1) *rr = *ss++;
  /* #87: @5 = 0 */
  w5 = 0.;
  /* #88: (@25[14] = @5) */
  for (rr=w25+14, ss=(&w5); rr!=w25+15; rr+=1) *rr = *ss++;
  /* #89: @5 = 0 */
  w5 = 0.;
  /* #90: (@25[3] = @5) */
  for (rr=w25+3, ss=(&w5); rr!=w25+4; rr+=1) *rr = *ss++;
  /* #91: @5 = 0 */
  w5 = 0.;
  /* #92: (@25[7] = @5) */
  for (rr=w25+7, ss=(&w5); rr!=w25+8; rr+=1) *rr = *ss++;
  /* #93: @5 = 0 */
  w5 = 0.;
  /* #94: (@25[11] = @5) */
  for (rr=w25+11, ss=(&w5); rr!=w25+12; rr+=1) *rr = *ss++;
  /* #95: @5 = 1 */
  w5 = 1.;
  /* #96: (@25[15] = @5) */
  for (rr=w25+15, ss=(&w5); rr!=w25+16; rr+=1) *rr = *ss++;
  /* #97: @26 = horzcat(@24, @25) */
  rr=w26;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<16; ++i) *rr++ = *cs++;
  /* #98: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #99: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #100: @25 = zeros(4x4) */
  casadi_clear(w25, 16);
  /* #101: @28 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 16, w28);
  /* #102: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #103: @5 = 0.6756 */
  w5 = 6.7559999999999998e-01;
  /* #104: (@29[0] = @5) */
  for (rr=w29+0, ss=(&w5); rr!=w29+1; rr+=1) *rr = *ss++;
  /* #105: @5 = 0 */
  w5 = 0.;
  /* #106: (@29[4] = @5) */
  for (rr=w29+4, ss=(&w5); rr!=w29+5; rr+=1) *rr = *ss++;
  /* #107: @5 = 0 */
  w5 = 0.;
  /* #108: (@29[8] = @5) */
  for (rr=w29+8, ss=(&w5); rr!=w29+9; rr+=1) *rr = *ss++;
  /* #109: @5 = 0 */
  w5 = 0.;
  /* #110: (@29[12] = @5) */
  for (rr=w29+12, ss=(&w5); rr!=w29+13; rr+=1) *rr = *ss++;
  /* #111: @5 = 0 */
  w5 = 0.;
  /* #112: (@29[1] = @5) */
  for (rr=w29+1, ss=(&w5); rr!=w29+2; rr+=1) *rr = *ss++;
  /* #113: @5 = 0.6344 */
  w5 = 6.3439999999999996e-01;
  /* #114: (@29[5] = @5) */
  for (rr=w29+5, ss=(&w5); rr!=w29+6; rr+=1) *rr = *ss++;
  /* #115: @5 = 0 */
  w5 = 0.;
  /* #116: (@29[9] = @5) */
  for (rr=w29+9, ss=(&w5); rr!=w29+10; rr+=1) *rr = *ss++;
  /* #117: @5 = 0 */
  w5 = 0.;
  /* #118: (@29[13] = @5) */
  for (rr=w29+13, ss=(&w5); rr!=w29+14; rr+=1) *rr = *ss++;
  /* #119: @5 = 0 */
  w5 = 0.;
  /* #120: (@29[2] = @5) */
  for (rr=w29+2, ss=(&w5); rr!=w29+3; rr+=1) *rr = *ss++;
  /* #121: @5 = 0 */
  w5 = 0.;
  /* #122: (@29[6] = @5) */
  for (rr=w29+6, ss=(&w5); rr!=w29+7; rr+=1) *rr = *ss++;
  /* #123: @5 = 0.408 */
  w5 = 4.0799999999999997e-01;
  /* #124: (@29[10] = @5) */
  for (rr=w29+10, ss=(&w5); rr!=w29+11; rr+=1) *rr = *ss++;
  /* #125: @5 = 0 */
  w5 = 0.;
  /* #126: (@29[14] = @5) */
  for (rr=w29+14, ss=(&w5); rr!=w29+15; rr+=1) *rr = *ss++;
  /* #127: @5 = 0 */
  w5 = 0.;
  /* #128: (@29[3] = @5) */
  for (rr=w29+3, ss=(&w5); rr!=w29+4; rr+=1) *rr = *ss++;
  /* #129: @5 = 0 */
  w5 = 0.;
  /* #130: (@29[7] = @5) */
  for (rr=w29+7, ss=(&w5); rr!=w29+8; rr+=1) *rr = *ss++;
  /* #131: @5 = 0 */
  w5 = 0.;
  /* #132: (@29[11] = @5) */
  for (rr=w29+11, ss=(&w5); rr!=w29+12; rr+=1) *rr = *ss++;
  /* #133: @5 = 0.2953 */
  w5 = 2.9530000000000001e-01;
  /* #134: (@29[15] = @5) */
  for (rr=w29+15, ss=(&w5); rr!=w29+16; rr+=1) *rr = *ss++;
  /* #135: @28 = (@29\@28) */
  rr = w28;
  ss = w29;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #136: @30 = zeros(4x4) */
  casadi_clear(w30, 16);
  /* #137: @5 = 0.5941 */
  w5 = 5.9409999999999996e-01;
  /* #138: (@30[0] = @5) */
  for (rr=w30+0, ss=(&w5); rr!=w30+1; rr+=1) *rr = *ss++;
  /* #139: @5 = -0.8109 */
  w5 = -8.1089999999999995e-01;
  /* #140: @6 = (@5*@12) */
  w6  = (w5*w12);
  /* #141: (@30[4] = @6) */
  for (rr=w30+4, ss=(&w6); rr!=w30+5; rr+=1) *rr = *ss++;
  /* #142: @6 = 0 */
  w6 = 0.;
  /* #143: (@30[8] = @6) */
  for (rr=w30+8, ss=(&w6); rr!=w30+9; rr+=1) *rr = *ss++;
  /* #144: @6 = 0 */
  w6 = 0.;
  /* #145: (@30[12] = @6) */
  for (rr=w30+12, ss=(&w6); rr!=w30+13; rr+=1) *rr = *ss++;
  /* #146: @6 = 0.3984 */
  w6 = 3.9839999999999998e-01;
  /* #147: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #148: (@30[1] = @12) */
  for (rr=w30+1, ss=(&w12); rr!=w30+2; rr+=1) *rr = *ss++;
  /* #149: @12 = 0.704 */
  w12 = 7.0399999999999996e-01;
  /* #150: (@30[5] = @12) */
  for (rr=w30+5, ss=(&w12); rr!=w30+6; rr+=1) *rr = *ss++;
  /* #151: @12 = 0 */
  w12 = 0.;
  /* #152: (@30[9] = @12) */
  for (rr=w30+9, ss=(&w12); rr!=w30+10; rr+=1) *rr = *ss++;
  /* #153: @12 = 0 */
  w12 = 0.;
  /* #154: (@30[13] = @12) */
  for (rr=w30+13, ss=(&w12); rr!=w30+14; rr+=1) *rr = *ss++;
  /* #155: @12 = 0 */
  w12 = 0.;
  /* #156: (@30[2] = @12) */
  for (rr=w30+2, ss=(&w12); rr!=w30+3; rr+=1) *rr = *ss++;
  /* #157: @12 = 0 */
  w12 = 0.;
  /* #158: (@30[6] = @12) */
  for (rr=w30+6, ss=(&w12); rr!=w30+7; rr+=1) *rr = *ss++;
  /* #159: @12 = 0.9365 */
  w12 = 9.3650000000000000e-01;
  /* #160: (@30[10] = @12) */
  for (rr=w30+10, ss=(&w12); rr!=w30+11; rr+=1) *rr = *ss++;
  /* #161: @12 = 0 */
  w12 = 0.;
  /* #162: (@30[14] = @12) */
  for (rr=w30+14, ss=(&w12); rr!=w30+15; rr+=1) *rr = *ss++;
  /* #163: @12 = 0 */
  w12 = 0.;
  /* #164: (@30[3] = @12) */
  for (rr=w30+3, ss=(&w12); rr!=w30+4; rr+=1) *rr = *ss++;
  /* #165: @12 = 0 */
  w12 = 0.;
  /* #166: (@30[7] = @12) */
  for (rr=w30+7, ss=(&w12); rr!=w30+8; rr+=1) *rr = *ss++;
  /* #167: @12 = 0 */
  w12 = 0.;
  /* #168: (@30[11] = @12) */
  for (rr=w30+11, ss=(&w12); rr!=w30+12; rr+=1) *rr = *ss++;
  /* #169: @12 = 0.9752 */
  w12 = 9.7519999999999996e-01;
  /* #170: (@30[15] = @12) */
  for (rr=w30+15, ss=(&w12); rr!=w30+16; rr+=1) *rr = *ss++;
  /* #171: @25 = mac(@28,@30,@25) */
  for (i=0, rr=w25; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #172: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<16; ++i) *rr++ = (- *cs++ );
  /* #173: @26 = horzcat(@24, @25) */
  rr=w26;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<16; ++i) *rr++ = *cs++;
  /* #174: @31 = @26' */
  for (i=0, rr=w31, cs=w26; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #175: @32 = horzcat(@27, @31) */
  rr=w32;
  for (i=0, cs=w27; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<32; ++i) *rr++ = *cs++;
  /* #176: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #177: @2 = mac(@33,@19,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w33+j, tt=w19+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #178: @0 = mac(@20,@2,@0) */
  casadi_mtimes(w20, casadi_s6, w2, casadi_s5, (&w0), casadi_s4, w, 0);
  /* #179: @12 = 0 */
  w12 = 0.;
  /* #180: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #181: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #182: @25 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 16, w25);
  /* #183: @25 = (@29\@25) */
  rr = w25;
  ss = w29;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #184: @29 = @25' */
  for (i=0, rr=w29, cs=w25; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #185: @27 = horzcat(@24, @29) */
  rr=w27;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<16; ++i) *rr++ = *cs++;
  /* #186: @31 = @27' */
  for (i=0, rr=w31, cs=w27; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #187: @22 = mac(@20,@31,@22) */
  casadi_mtimes(w20, casadi_s6, w31, casadi_s8, w22, casadi_s7, w, 0);
  /* #188: @7 = input[1][0] */
  w7 = arg[1] ? arg[1][0] : 0;
  /* #189: @9 = input[1][1] */
  w9 = arg[1] ? arg[1][1] : 0;
  /* #190: @10 = input[1][2] */
  w10 = arg[1] ? arg[1][2] : 0;
  /* #191: @11 = input[1][3] */
  w11 = arg[1] ? arg[1][3] : 0;
  /* #192: @20 = vertcat(@7, @9, @10, @11) */
  rr=w20;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #193: @12 = mac(@22,@20,@12) */
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #194: @0 = (@0+@12) */
  w0 += w12;
  /* #195: @12 = 0.1 */
  w12 = 1.0000000000000001e-01;
  /* #196: @7 = 0 */
  w7 = 0.;
  /* #197: @7 = mac(@3,@18,@7) */
  for (i=0, rr=(&w7); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #198: @12 = (@12*@7) */
  w12 *= w7;
  /* #199: @0 = (@0+@12) */
  w0 += w12;
  /* #200: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #201: @17 = zeros(12x1) */
  casadi_clear(w17, 12);
  /* #202: @22 = @22' */
  /* #203: {@0, @12, @7, @9} = vertsplit(@22) */
  w0 = w22[0];
  w12 = w22[1];
  w7 = w22[2];
  w9 = w22[3];
  /* #204: (@17[0] = @0) */
  for (rr=w17+0, ss=(&w0); rr!=w17+1; rr+=1) *rr = *ss++;
  /* #205: (@17[1] = @12) */
  for (rr=w17+1, ss=(&w12); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #206: (@17[2] = @7) */
  for (rr=w17+2, ss=(&w7); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #207: (@17[3] = @9) */
  for (rr=w17+3, ss=(&w9); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #208: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #209: @35 = dense(@1) */
  casadi_densify(w1, casadi_s9, w35, 0);
  /* #210: @34 = mac(@32,@35,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w32+j, tt=w35+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #211: @9 = 0.1 */
  w9 = 1.0000000000000001e-01;
  /* #212: @3 = @3' */
  /* #213: @3 = (@9*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #214: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #215: @36 = zeros(8x1) */
  casadi_clear(w36, 8);
  /* #216: @22 = zeros(1x8,4nz) */
  casadi_clear(w22, 4);
  /* #217: @20 = @20' */
  /* #218: @22 = mac(@20,@27,@22) */
  casadi_mtimes(w20, casadi_s7, w27, casadi_s10, w22, casadi_s6, w, 0);
  /* #219: @37 = dense(@22) */
  casadi_densify(w22, casadi_s6, w37, 0);
  /* #220: @2 = @2' */
  /* #221: @37 = (@37+@2) */
  for (i=0, rr=w37, cs=w2; i<8; ++i) (*rr++) += (*cs++);
  /* #222: @37 = @37' */
  /* #223: @7 = @37[3] */
  for (rr=(&w7), ss=w37+3; ss!=w37+4; ss+=1) *rr++ = *ss;
  /* #224: (@36[3] += @7) */
  for (rr=w36+3, ss=(&w7); rr!=w36+4; rr+=1) *rr += *ss++;
  /* #225: @7 = 0 */
  w7 = 0.;
  /* #226: (@37[3] = @7) */
  for (rr=w37+3, ss=(&w7); rr!=w37+4; rr+=1) *rr = *ss++;
  /* #227: @7 = @37[2] */
  for (rr=(&w7), ss=w37+2; ss!=w37+3; ss+=1) *rr++ = *ss;
  /* #228: (@36[2] += @7) */
  for (rr=w36+2, ss=(&w7); rr!=w36+3; rr+=1) *rr += *ss++;
  /* #229: @7 = 0 */
  w7 = 0.;
  /* #230: (@37[2] = @7) */
  for (rr=w37+2, ss=(&w7); rr!=w37+3; rr+=1) *rr = *ss++;
  /* #231: @7 = @37[1] */
  for (rr=(&w7), ss=w37+1; ss!=w37+2; ss+=1) *rr++ = *ss;
  /* #232: (@36[1] += @7) */
  for (rr=w36+1, ss=(&w7); rr!=w36+2; rr+=1) *rr += *ss++;
  /* #233: @7 = 0 */
  w7 = 0.;
  /* #234: (@37[1] = @7) */
  for (rr=w37+1, ss=(&w7); rr!=w37+2; rr+=1) *rr = *ss++;
  /* #235: @7 = @37[0] */
  for (rr=(&w7), ss=w37+0; ss!=w37+1; ss+=1) *rr++ = *ss;
  /* #236: (@36[0] += @7) */
  for (rr=w36+0, ss=(&w7); rr!=w36+1; rr+=1) *rr += *ss++;
  /* #237: @22 = @36[:4] */
  for (rr=w22, ss=w36+0; ss!=w36+4; ss+=1) *rr++ = *ss;
  /* #238: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<4; ++i) *rr++ = (- *cs++ );
  /* #239: @20 = @22' */
  casadi_copy(w22, 4, w20);
  /* #240: @20 = (@4*@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #241: @1 = mac(@20,@21,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #242: @1 = @1' */
  /* #243: @3 = (@3+@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #244: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #245: @18 = @18' */
  /* #246: @18 = (@9*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #247: @22 = @22' */
  /* #248: @18 = (@18+@22) */
  for (i=0, rr=w18, cs=w22; i<4; ++i) (*rr++) += (*cs++);
  /* #249: @24 = @21' */
  for (i=0, rr=w24, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #250: @1 = mac(@18,@24,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #251: @1 = (@4*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #252: @1 = @1' */
  /* #253: @3 = (@3+@1) */
  for (i=0, rr=w3, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #254: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) *rr++ = (- *cs++ );
  /* #255: (@34[:4] += @3) */
  for (rr=w34+0, ss=w3; rr!=w34+4; rr+=1) *rr += *ss++;
  /* #256: {@4, @9, @7, @12, @0, @10, @11, @13} = vertsplit(@34) */
  w4 = w34[0];
  w9 = w34[1];
  w7 = w34[2];
  w12 = w34[3];
  w0 = w34[4];
  w10 = w34[5];
  w11 = w34[6];
  w13 = w34[7];
  /* #257: (@17[4] = @4) */
  for (rr=w17+4, ss=(&w4); rr!=w17+5; rr+=1) *rr = *ss++;
  /* #258: (@17[5] = @9) */
  for (rr=w17+5, ss=(&w9); rr!=w17+6; rr+=1) *rr = *ss++;
  /* #259: (@17[6] = @7) */
  for (rr=w17+6, ss=(&w7); rr!=w17+7; rr+=1) *rr = *ss++;
  /* #260: @7 = cos(@8) */
  w7 = cos( w8 );
  /* #261: @32 = zeros(8x8) */
  casadi_clear(w32, 64);
  /* #262: @19 = @19' */
  /* #263: @32 = mac(@35,@19,@32) */
  for (i=0, rr=w32; i<8; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w35+j, tt=w19+i*1; k<1; ++k) *rr += ss[k*8]**tt++;
  /* #264: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #265: {@27, @31} = horzsplit(@33) */
  casadi_copy(w33, 32, w27);
  casadi_copy(w33+32, 32, w31);
  /* #266: @26 = @27' */
  for (i=0, rr=w26, cs=w27; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #267: {NULL, @24} = horzsplit(@26) */
  casadi_copy(w26+16, 16, w24);
  /* #268: @9 = 0 */
  w9 = 0.;
  /* #269: (@24[15] = @9) */
  for (rr=w24+15, ss=(&w9); rr!=w24+16; rr+=1) *rr = *ss++;
  /* #270: @9 = 0 */
  w9 = 0.;
  /* #271: (@24[11] = @9) */
  for (rr=w24+11, ss=(&w9); rr!=w24+12; rr+=1) *rr = *ss++;
  /* #272: @9 = 0 */
  w9 = 0.;
  /* #273: (@24[7] = @9) */
  for (rr=w24+7, ss=(&w9); rr!=w24+8; rr+=1) *rr = *ss++;
  /* #274: @9 = 0 */
  w9 = 0.;
  /* #275: (@24[3] = @9) */
  for (rr=w24+3, ss=(&w9); rr!=w24+4; rr+=1) *rr = *ss++;
  /* #276: @9 = 0 */
  w9 = 0.;
  /* #277: (@24[14] = @9) */
  for (rr=w24+14, ss=(&w9); rr!=w24+15; rr+=1) *rr = *ss++;
  /* #278: @9 = 0 */
  w9 = 0.;
  /* #279: (@24[10] = @9) */
  for (rr=w24+10, ss=(&w9); rr!=w24+11; rr+=1) *rr = *ss++;
  /* #280: @9 = 0 */
  w9 = 0.;
  /* #281: (@24[6] = @9) */
  for (rr=w24+6, ss=(&w9); rr!=w24+7; rr+=1) *rr = *ss++;
  /* #282: @9 = 0 */
  w9 = 0.;
  /* #283: (@24[2] = @9) */
  for (rr=w24+2, ss=(&w9); rr!=w24+3; rr+=1) *rr = *ss++;
  /* #284: @9 = 0 */
  w9 = 0.;
  /* #285: (@24[13] = @9) */
  for (rr=w24+13, ss=(&w9); rr!=w24+14; rr+=1) *rr = *ss++;
  /* #286: @9 = 0 */
  w9 = 0.;
  /* #287: (@24[9] = @9) */
  for (rr=w24+9, ss=(&w9); rr!=w24+10; rr+=1) *rr = *ss++;
  /* #288: @9 = 0 */
  w9 = 0.;
  /* #289: @21 = @24; (@21[5] = @9) */
  casadi_copy(w24, 16, w21);
  for (rr=w21+5, ss=(&w9); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #290: @9 = @21[1] */
  for (rr=(&w9), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #291: @7 = (@7*@9) */
  w7 *= w9;
  /* #292: @9 = sin(@8) */
  w9 = sin( w8 );
  /* #293: @4 = @24[5] */
  for (rr=(&w4), ss=w24+5; ss!=w24+6; ss+=1) *rr++ = *ss;
  /* #294: @9 = (@9*@4) */
  w9 *= w4;
  /* #295: @7 = (@7-@9) */
  w7 -= w9;
  /* #296: @9 = cos(@8) */
  w9 = cos( w8 );
  /* #297: @4 = 0 */
  w4 = 0.;
  /* #298: (@21[1] = @4) */
  for (rr=w21+1, ss=(&w4); rr!=w21+2; rr+=1) *rr = *ss++;
  /* #299: @4 = 0 */
  w4 = 0.;
  /* #300: (@21[12] = @4) */
  for (rr=w21+12, ss=(&w4); rr!=w21+13; rr+=1) *rr = *ss++;
  /* #301: @4 = 0 */
  w4 = 0.;
  /* #302: (@21[8] = @4) */
  for (rr=w21+8, ss=(&w4); rr!=w21+9; rr+=1) *rr = *ss++;
  /* #303: @4 = @21[4] */
  for (rr=(&w4), ss=w21+4; ss!=w21+5; ss+=1) *rr++ = *ss;
  /* #304: @9 = (@9*@4) */
  w9 *= w4;
  /* #305: @7 = (@7-@9) */
  w7 -= w9;
  /* #306: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #307: @9 = 0 */
  w9 = 0.;
  /* #308: (@21[4] = @9) */
  for (rr=w21+4, ss=(&w9); rr!=w21+5; rr+=1) *rr = *ss++;
  /* #309: @9 = @21[0] */
  for (rr=(&w9), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #310: @8 = (@8*@9) */
  w8 *= w9;
  /* #311: @7 = (@7-@8) */
  w7 -= w8;
  /* #312: @7 = (@7+@12) */
  w7 += w12;
  /* #313: (@17[7] = @7) */
  for (rr=w17+7, ss=(&w7); rr!=w17+8; rr+=1) *rr = *ss++;
  /* #314: (@17[8] = @0) */
  for (rr=w17+8, ss=(&w0); rr!=w17+9; rr+=1) *rr = *ss++;
  /* #315: (@17[9] = @10) */
  for (rr=w17+9, ss=(&w10); rr!=w17+10; rr+=1) *rr = *ss++;
  /* #316: (@17[10] = @11) */
  for (rr=w17+10, ss=(&w11); rr!=w17+11; rr+=1) *rr = *ss++;
  /* #317: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #318: @24 = @28' */
  for (i=0, rr=w24, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #319: @26 = @31' */
  for (i=0, rr=w26, cs=w31; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #320: {NULL, @28} = horzsplit(@26) */
  casadi_copy(w26+16, 16, w28);
  /* #321: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<16; ++i) *rr++ = (- *cs++ );
  /* #322: @21 = mac(@24,@28,@21) */
  for (i=0, rr=w21; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w24+j, tt=w28+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #323: @11 = 0 */
  w11 = 0.;
  /* #324: (@21[15] = @11) */
  for (rr=w21+15, ss=(&w11); rr!=w21+16; rr+=1) *rr = *ss++;
  /* #325: @11 = 0 */
  w11 = 0.;
  /* #326: (@21[11] = @11) */
  for (rr=w21+11, ss=(&w11); rr!=w21+12; rr+=1) *rr = *ss++;
  /* #327: @11 = 0 */
  w11 = 0.;
  /* #328: (@21[7] = @11) */
  for (rr=w21+7, ss=(&w11); rr!=w21+8; rr+=1) *rr = *ss++;
  /* #329: @11 = 0 */
  w11 = 0.;
  /* #330: (@21[3] = @11) */
  for (rr=w21+3, ss=(&w11); rr!=w21+4; rr+=1) *rr = *ss++;
  /* #331: @11 = 0 */
  w11 = 0.;
  /* #332: (@21[14] = @11) */
  for (rr=w21+14, ss=(&w11); rr!=w21+15; rr+=1) *rr = *ss++;
  /* #333: @11 = 0 */
  w11 = 0.;
  /* #334: (@21[10] = @11) */
  for (rr=w21+10, ss=(&w11); rr!=w21+11; rr+=1) *rr = *ss++;
  /* #335: @11 = 0 */
  w11 = 0.;
  /* #336: (@21[6] = @11) */
  for (rr=w21+6, ss=(&w11); rr!=w21+7; rr+=1) *rr = *ss++;
  /* #337: @11 = 0 */
  w11 = 0.;
  /* #338: (@21[2] = @11) */
  for (rr=w21+2, ss=(&w11); rr!=w21+3; rr+=1) *rr = *ss++;
  /* #339: @11 = 0 */
  w11 = 0.;
  /* #340: (@21[13] = @11) */
  for (rr=w21+13, ss=(&w11); rr!=w21+14; rr+=1) *rr = *ss++;
  /* #341: @11 = 0 */
  w11 = 0.;
  /* #342: (@21[9] = @11) */
  for (rr=w21+9, ss=(&w11); rr!=w21+10; rr+=1) *rr = *ss++;
  /* #343: @11 = 0 */
  w11 = 0.;
  /* #344: (@21[5] = @11) */
  for (rr=w21+5, ss=(&w11); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #345: @11 = @21[1] */
  for (rr=(&w11), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #346: @6 = (@6*@11) */
  w6 *= w11;
  /* #347: @11 = 0 */
  w11 = 0.;
  /* #348: (@21[1] = @11) */
  for (rr=w21+1, ss=(&w11); rr!=w21+2; rr+=1) *rr = *ss++;
  /* #349: @11 = 0 */
  w11 = 0.;
  /* #350: (@21[12] = @11) */
  for (rr=w21+12, ss=(&w11); rr!=w21+13; rr+=1) *rr = *ss++;
  /* #351: @11 = 0 */
  w11 = 0.;
  /* #352: (@21[8] = @11) */
  for (rr=w21+8, ss=(&w11); rr!=w21+9; rr+=1) *rr = *ss++;
  /* #353: @11 = @21[4] */
  for (rr=(&w11), ss=w21+4; ss!=w21+5; ss+=1) *rr++ = *ss;
  /* #354: @5 = (@5*@11) */
  w5 *= w11;
  /* #355: @6 = (@6+@5) */
  w6 += w5;
  /* #356: @6 = (@6+@13) */
  w6 += w13;
  /* #357: (@17[11] = @6) */
  for (rr=w17+11, ss=(&w6); rr!=w17+12; rr+=1) *rr = *ss++;
  /* #358: output[1][0] = @17 */
  casadi_copy(w17, 12, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_constr_h_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s13;
    case 2: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 426;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
