/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s6[15] = {1, 8, 0, 1, 2, 3, 4, 4, 4, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s7[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s8[39] = {8, 4, 0, 8, 16, 24, 32, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s9[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s10[3] = {0, 0, 0};
static const casadi_int casadi_s11[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

static const casadi_real casadi_c0[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_constr_h_fun:(i0[8],i1[4],i2[],i3[12])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+9, *w2=w+13, *w3=w+21, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+38, *w18=w+50, *w19=w+54, *w20=w+62, *w21=w+66, *w22=w+82, *w23=w+86, *w24=w+90, *w25=w+106, *w26=w+138, *w27=w+170, *w28=w+186, *w29=w+202, *w30=w+218, *w31=w+250, *w32=w+314;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(8x1,4nz) */
  casadi_clear(w1, 4);
  /* #2: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #3: @3 = zeros(1x4) */
  casadi_clear(w3, 4);
  /* #4: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #5: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #6: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #7: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #8: @8 = input[3][3] */
  w8 = arg[3] ? arg[3][3] : 0;
  /* #9: @9 = input[3][4] */
  w9 = arg[3] ? arg[3][4] : 0;
  /* #10: @10 = input[3][5] */
  w10 = arg[3] ? arg[3][5] : 0;
  /* #11: @11 = input[3][6] */
  w11 = arg[3] ? arg[3][6] : 0;
  /* #12: @12 = input[3][7] */
  w12 = arg[3] ? arg[3][7] : 0;
  /* #13: @13 = input[3][8] */
  w13 = arg[3] ? arg[3][8] : 0;
  /* #14: @14 = input[3][9] */
  w14 = arg[3] ? arg[3][9] : 0;
  /* #15: @15 = input[3][10] */
  w15 = arg[3] ? arg[3][10] : 0;
  /* #16: @16 = input[3][11] */
  w16 = arg[3] ? arg[3][11] : 0;
  /* #17: @17 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:4] */
  for (rr=w18, ss=w17+0; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #19: @5 = input[0][0] */
  w5 = arg[0] ? arg[0][0] : 0;
  /* #20: @6 = input[0][1] */
  w6 = arg[0] ? arg[0][1] : 0;
  /* #21: @7 = input[0][2] */
  w7 = arg[0] ? arg[0][2] : 0;
  /* #22: @8 = input[0][3] */
  w8 = arg[0] ? arg[0][3] : 0;
  /* #23: @9 = input[0][4] */
  w9 = arg[0] ? arg[0][4] : 0;
  /* #24: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #25: @11 = input[0][6] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #26: @12 = input[0][7] */
  w12 = arg[0] ? arg[0][7] : 0;
  /* #27: @19 = vertcat(@5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w19;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #28: @20 = @19[:4] */
  for (rr=w20, ss=w19+0; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #29: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<4; ++i) (*rr++) -= (*cs++);
  /* #30: @20 = @18' */
  casadi_copy(w18, 4, w20);
  /* #31: @20 = (@4*@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #32: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #33: @5 = 2 */
  w5 = 2.;
  /* #34: (@21[0] = @5) */
  for (rr=w21+0, ss=(&w5); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #35: @5 = 2 */
  w5 = 2.;
  /* #36: (@21[5] = @5) */
  for (rr=w21+5, ss=(&w5); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #37: @5 = 2 */
  w5 = 2.;
  /* #38: (@21[10] = @5) */
  for (rr=w21+10, ss=(&w5); rr!=w21+11; rr+=1) *rr = *ss++;
  /* #39: @5 = 2 */
  w5 = 2.;
  /* #40: (@21[15] = @5) */
  for (rr=w21+15, ss=(&w5); rr!=w21+16; rr+=1) *rr = *ss++;
  /* #41: @3 = mac(@20,@21,@3) */
  for (i=0, rr=w3; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #42: @20 = @3' */
  casadi_copy(w3, 4, w20);
  /* #43: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #44: @23 = @18' */
  casadi_copy(w18, 4, w23);
  /* #45: @24 = @21' */
  for (i=0, rr=w24, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #46: @22 = mac(@23,@24,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #47: @22 = (@4*@22) */
  for (i=0, rr=w22, cs=w22; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #48: @22 = @22' */
  /* #49: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<4; ++i) (*rr++) += (*cs++);
  /* #50: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #51: (@2[:4] += @20) */
  for (rr=w2+0, ss=w20; rr!=w2+4; rr+=1) *rr += *ss++;
  /* #52: @4 = @2[0] */
  for (rr=(&w4), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #53: (@1[0] = @4) */
  for (rr=w1+0, ss=(&w4); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #54: @4 = @2[1] */
  for (rr=(&w4), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #55: (@1[1] = @4) */
  for (rr=w1+1, ss=(&w4); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #56: @4 = @2[2] */
  for (rr=(&w4), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #57: (@1[2] = @4) */
  for (rr=w1+2, ss=(&w4); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #58: @4 = @2[3] */
  for (rr=(&w4), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #59: (@1[3] = @4) */
  for (rr=w1+3, ss=(&w4); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #60: @1 = @1' */
  /* #61: @2 = zeros(8x1) */
  casadi_clear(w2, 8);
  /* #62: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #63: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #64: @4 = cos(@8) */
  w4 = cos( w8 );
  /* #65: (@21[0] = @4) */
  for (rr=w21+0, ss=(&w4); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #66: @4 = sin(@8) */
  w4 = sin( w8 );
  /* #67: @4 = (-@4) */
  w4 = (- w4 );
  /* #68: (@21[4] = @4) */
  for (rr=w21+4, ss=(&w4); rr!=w21+5; rr+=1) *rr = *ss++;
  /* #69: @4 = 0 */
  w4 = 0.;
  /* #70: (@21[8] = @4) */
  for (rr=w21+8, ss=(&w4); rr!=w21+9; rr+=1) *rr = *ss++;
  /* #71: @4 = 0 */
  w4 = 0.;
  /* #72: (@21[12] = @4) */
  for (rr=w21+12, ss=(&w4); rr!=w21+13; rr+=1) *rr = *ss++;
  /* #73: @4 = sin(@8) */
  w4 = sin( w8 );
  /* #74: (@21[1] = @4) */
  for (rr=w21+1, ss=(&w4); rr!=w21+2; rr+=1) *rr = *ss++;
  /* #75: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #76: (@21[5] = @8) */
  for (rr=w21+5, ss=(&w8); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #77: @8 = 0 */
  w8 = 0.;
  /* #78: (@21[9] = @8) */
  for (rr=w21+9, ss=(&w8); rr!=w21+10; rr+=1) *rr = *ss++;
  /* #79: @8 = 0 */
  w8 = 0.;
  /* #80: (@21[13] = @8) */
  for (rr=w21+13, ss=(&w8); rr!=w21+14; rr+=1) *rr = *ss++;
  /* #81: @8 = 0 */
  w8 = 0.;
  /* #82: (@21[2] = @8) */
  for (rr=w21+2, ss=(&w8); rr!=w21+3; rr+=1) *rr = *ss++;
  /* #83: @8 = 0 */
  w8 = 0.;
  /* #84: (@21[6] = @8) */
  for (rr=w21+6, ss=(&w8); rr!=w21+7; rr+=1) *rr = *ss++;
  /* #85: @8 = 1 */
  w8 = 1.;
  /* #86: (@21[10] = @8) */
  for (rr=w21+10, ss=(&w8); rr!=w21+11; rr+=1) *rr = *ss++;
  /* #87: @8 = 0 */
  w8 = 0.;
  /* #88: (@21[14] = @8) */
  for (rr=w21+14, ss=(&w8); rr!=w21+15; rr+=1) *rr = *ss++;
  /* #89: @8 = 0 */
  w8 = 0.;
  /* #90: (@21[3] = @8) */
  for (rr=w21+3, ss=(&w8); rr!=w21+4; rr+=1) *rr = *ss++;
  /* #91: @8 = 0 */
  w8 = 0.;
  /* #92: (@21[7] = @8) */
  for (rr=w21+7, ss=(&w8); rr!=w21+8; rr+=1) *rr = *ss++;
  /* #93: @8 = 0 */
  w8 = 0.;
  /* #94: (@21[11] = @8) */
  for (rr=w21+11, ss=(&w8); rr!=w21+12; rr+=1) *rr = *ss++;
  /* #95: @8 = 1 */
  w8 = 1.;
  /* #96: (@21[15] = @8) */
  for (rr=w21+15, ss=(&w8); rr!=w21+16; rr+=1) *rr = *ss++;
  /* #97: @25 = horzcat(@24, @21) */
  rr=w25;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  /* #98: @26 = @25' */
  for (i=0, rr=w26, cs=w25; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #99: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #100: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #101: @27 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 16, w27);
  /* #102: @28 = zeros(4x4) */
  casadi_clear(w28, 16);
  /* #103: @8 = 0.6756 */
  w8 = 6.7559999999999998e-01;
  /* #104: (@28[0] = @8) */
  for (rr=w28+0, ss=(&w8); rr!=w28+1; rr+=1) *rr = *ss++;
  /* #105: @8 = 0 */
  w8 = 0.;
  /* #106: (@28[4] = @8) */
  for (rr=w28+4, ss=(&w8); rr!=w28+5; rr+=1) *rr = *ss++;
  /* #107: @8 = 0 */
  w8 = 0.;
  /* #108: (@28[8] = @8) */
  for (rr=w28+8, ss=(&w8); rr!=w28+9; rr+=1) *rr = *ss++;
  /* #109: @8 = 0 */
  w8 = 0.;
  /* #110: (@28[12] = @8) */
  for (rr=w28+12, ss=(&w8); rr!=w28+13; rr+=1) *rr = *ss++;
  /* #111: @8 = 0 */
  w8 = 0.;
  /* #112: (@28[1] = @8) */
  for (rr=w28+1, ss=(&w8); rr!=w28+2; rr+=1) *rr = *ss++;
  /* #113: @8 = 0.6344 */
  w8 = 6.3439999999999996e-01;
  /* #114: (@28[5] = @8) */
  for (rr=w28+5, ss=(&w8); rr!=w28+6; rr+=1) *rr = *ss++;
  /* #115: @8 = 0 */
  w8 = 0.;
  /* #116: (@28[9] = @8) */
  for (rr=w28+9, ss=(&w8); rr!=w28+10; rr+=1) *rr = *ss++;
  /* #117: @8 = 0 */
  w8 = 0.;
  /* #118: (@28[13] = @8) */
  for (rr=w28+13, ss=(&w8); rr!=w28+14; rr+=1) *rr = *ss++;
  /* #119: @8 = 0 */
  w8 = 0.;
  /* #120: (@28[2] = @8) */
  for (rr=w28+2, ss=(&w8); rr!=w28+3; rr+=1) *rr = *ss++;
  /* #121: @8 = 0 */
  w8 = 0.;
  /* #122: (@28[6] = @8) */
  for (rr=w28+6, ss=(&w8); rr!=w28+7; rr+=1) *rr = *ss++;
  /* #123: @8 = 0.408 */
  w8 = 4.0799999999999997e-01;
  /* #124: (@28[10] = @8) */
  for (rr=w28+10, ss=(&w8); rr!=w28+11; rr+=1) *rr = *ss++;
  /* #125: @8 = 0 */
  w8 = 0.;
  /* #126: (@28[14] = @8) */
  for (rr=w28+14, ss=(&w8); rr!=w28+15; rr+=1) *rr = *ss++;
  /* #127: @8 = 0 */
  w8 = 0.;
  /* #128: (@28[3] = @8) */
  for (rr=w28+3, ss=(&w8); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #129: @8 = 0 */
  w8 = 0.;
  /* #130: (@28[7] = @8) */
  for (rr=w28+7, ss=(&w8); rr!=w28+8; rr+=1) *rr = *ss++;
  /* #131: @8 = 0 */
  w8 = 0.;
  /* #132: (@28[11] = @8) */
  for (rr=w28+11, ss=(&w8); rr!=w28+12; rr+=1) *rr = *ss++;
  /* #133: @8 = 0.2953 */
  w8 = 2.9530000000000001e-01;
  /* #134: (@28[15] = @8) */
  for (rr=w28+15, ss=(&w8); rr!=w28+16; rr+=1) *rr = *ss++;
  /* #135: @27 = (@28\@27) */
  rr = w27;
  ss = w28;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #136: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #137: @8 = 0.5941 */
  w8 = 5.9409999999999996e-01;
  /* #138: (@29[0] = @8) */
  for (rr=w29+0, ss=(&w8); rr!=w29+1; rr+=1) *rr = *ss++;
  /* #139: @8 = -0.8109 */
  w8 = -8.1089999999999995e-01;
  /* #140: @8 = (@8*@12) */
  w8 *= w12;
  /* #141: (@29[4] = @8) */
  for (rr=w29+4, ss=(&w8); rr!=w29+5; rr+=1) *rr = *ss++;
  /* #142: @8 = 0 */
  w8 = 0.;
  /* #143: (@29[8] = @8) */
  for (rr=w29+8, ss=(&w8); rr!=w29+9; rr+=1) *rr = *ss++;
  /* #144: @8 = 0 */
  w8 = 0.;
  /* #145: (@29[12] = @8) */
  for (rr=w29+12, ss=(&w8); rr!=w29+13; rr+=1) *rr = *ss++;
  /* #146: @8 = 0.3984 */
  w8 = 3.9839999999999998e-01;
  /* #147: @8 = (@8*@12) */
  w8 *= w12;
  /* #148: (@29[1] = @8) */
  for (rr=w29+1, ss=(&w8); rr!=w29+2; rr+=1) *rr = *ss++;
  /* #149: @8 = 0.704 */
  w8 = 7.0399999999999996e-01;
  /* #150: (@29[5] = @8) */
  for (rr=w29+5, ss=(&w8); rr!=w29+6; rr+=1) *rr = *ss++;
  /* #151: @8 = 0 */
  w8 = 0.;
  /* #152: (@29[9] = @8) */
  for (rr=w29+9, ss=(&w8); rr!=w29+10; rr+=1) *rr = *ss++;
  /* #153: @8 = 0 */
  w8 = 0.;
  /* #154: (@29[13] = @8) */
  for (rr=w29+13, ss=(&w8); rr!=w29+14; rr+=1) *rr = *ss++;
  /* #155: @8 = 0 */
  w8 = 0.;
  /* #156: (@29[2] = @8) */
  for (rr=w29+2, ss=(&w8); rr!=w29+3; rr+=1) *rr = *ss++;
  /* #157: @8 = 0 */
  w8 = 0.;
  /* #158: (@29[6] = @8) */
  for (rr=w29+6, ss=(&w8); rr!=w29+7; rr+=1) *rr = *ss++;
  /* #159: @8 = 0.9365 */
  w8 = 9.3650000000000000e-01;
  /* #160: (@29[10] = @8) */
  for (rr=w29+10, ss=(&w8); rr!=w29+11; rr+=1) *rr = *ss++;
  /* #161: @8 = 0 */
  w8 = 0.;
  /* #162: (@29[14] = @8) */
  for (rr=w29+14, ss=(&w8); rr!=w29+15; rr+=1) *rr = *ss++;
  /* #163: @8 = 0 */
  w8 = 0.;
  /* #164: (@29[3] = @8) */
  for (rr=w29+3, ss=(&w8); rr!=w29+4; rr+=1) *rr = *ss++;
  /* #165: @8 = 0 */
  w8 = 0.;
  /* #166: (@29[7] = @8) */
  for (rr=w29+7, ss=(&w8); rr!=w29+8; rr+=1) *rr = *ss++;
  /* #167: @8 = 0 */
  w8 = 0.;
  /* #168: (@29[11] = @8) */
  for (rr=w29+11, ss=(&w8); rr!=w29+12; rr+=1) *rr = *ss++;
  /* #169: @8 = 0.9752 */
  w8 = 9.7519999999999996e-01;
  /* #170: (@29[15] = @8) */
  for (rr=w29+15, ss=(&w8); rr!=w29+16; rr+=1) *rr = *ss++;
  /* #171: @21 = mac(@27,@29,@21) */
  for (i=0, rr=w21; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w27+j, tt=w29+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #172: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<16; ++i) *rr++ = (- *cs++ );
  /* #173: @25 = horzcat(@24, @21) */
  rr=w25;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  /* #174: @30 = @25' */
  for (i=0, rr=w30, cs=w25; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #175: @31 = horzcat(@26, @30) */
  rr=w31;
  for (i=0, cs=w26; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<32; ++i) *rr++ = *cs++;
  /* #176: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #177: @2 = mac(@32,@19,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w32+j, tt=w19+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #178: @0 = mac(@1,@2,@0) */
  casadi_mtimes(w1, casadi_s6, w2, casadi_s5, (&w0), casadi_s4, w, 0);
  /* #179: @8 = 0 */
  w8 = 0.;
  /* #180: @20 = zeros(1x4) */
  casadi_clear(w20, 4);
  /* #181: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #182: @21 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 16, w21);
  /* #183: @21 = (@28\@21) */
  rr = w21;
  ss = w28;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #184: @28 = @21' */
  for (i=0, rr=w28, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #185: @26 = horzcat(@24, @28) */
  rr=w26;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<16; ++i) *rr++ = *cs++;
  /* #186: @30 = @26' */
  for (i=0, rr=w30, cs=w26; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #187: @20 = mac(@1,@30,@20) */
  casadi_mtimes(w1, casadi_s6, w30, casadi_s8, w20, casadi_s7, w, 0);
  /* #188: @12 = input[1][0] */
  w12 = arg[1] ? arg[1][0] : 0;
  /* #189: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #190: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #191: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #192: @1 = vertcat(@12, @4, @5, @6) */
  rr=w1;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #193: @8 = mac(@20,@1,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w1+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #194: @0 = (@0+@8) */
  w0 += w8;
  /* #195: @8 = 0.1 */
  w8 = 1.0000000000000001e-01;
  /* #196: @12 = 0 */
  w12 = 0.;
  /* #197: @12 = mac(@3,@18,@12) */
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #198: @8 = (@8*@12) */
  w8 *= w12;
  /* #199: @0 = (@0+@8) */
  w0 += w8;
  /* #200: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    case 3: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 378;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
